---
settings:
  name: Active IQ Unified Manager 9.13
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - name: Unified Manager
    url: "/active-iq-unified-manager"
    version-number: '9.13'
  - name: Unified Manager
    url: "/active-iq-unified-manager-912"
    version-number: '9.12'
  - name: Unified Manager
    url: "/active-iq-unified-manager-911"
    version-number: '9.11'
  - name: Unified Manager
    url: "/active-iq-unified-manager-910"
    version-number: '9.10'
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Documenti di Active IQ Unified Manager 9.13
    url: "/index.html"
  - title: Note di rilascio
    url: "/reference_release_notes.html"
  - title: Inizia subito
    entries:
    - title: Installazione rapida per VMware vSphere
      url: "/install-vapp/qsg-vapp.html"
    - title: Installazione rapida per Linux
      url: "/install-linux/qsg-linux.html"
    - title: Installazione rapida per Windows
      url: "/install-windows/qsg-windows.html"
  - section: install-vapp
  - section: install-linux
  - section: install-windows
  - section: config
  - section: storage-mgmt
  - section: events
  - section: performance-checker
  - section: health-checker
  - section: data-protection
  - section: reporting
  - section: api-automation
  - title: Note legali
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Inizia subito
    links:
    - title: Panoramica del prodotto
      url: "/storage-mgmt/concept_introduction_to_unified_manager.html"
    - title: Note di rilascio
      url: reference_release_notes.html
    - title: Installazione rapida per VMware vSphere
      url: "/install-vapp/qsg-vapp.html"
    - title: Installazione rapida per Linux
      url: "/install-linux/qsg-linux.html"
    - title: Installazione rapida per Windows
      url: "/install-windows/qsg-windows.html"
  - title: Installare e configurare Unified Manager
    links:
    - title: Installazione e aggiornamento su sistemi VMware vSphere
      url: "/install-vapp/concept_requirements_for_installing_unified_manager.html"
    - title: Installazione e aggiornamento su sistemi Linux
      url: "/install-linux/concept_requirements_for_install_unified_manager.html"
    - title: Installazione e aggiornamento su sistemi Windows
      url: "/install-windows/concept_requirements_for_installing_unified_manager.html"
    - title: Configurare Unified Manager
      url: "/config/concept_configure_unified_manager.html"
    - title: Gestire le impostazioni delle funzioni
      url: "/config/concept_manage_feature_settings.html"
    - title: Gestire l'accesso in base al ruolo
      url: "/config/concept_manage_user_access.html"
  - title: Monitoraggio delle performance
    links:
    - title: Soglie di performance
      url: "/performance-checker/concept_manage_performance_thresholds.html"
    - title: Performance del cluster
      url: "/performance-checker/concept_monitor_cluster_performance_from_dashboard.html"
    - title: Gruppo di criteri QoS
      url: "/performance-checker/concept_manage_performance_using_qos_policy_group_information.html"
    - title: Workload Analyzer
      url: "/performance-checker/concept_troubleshooting_workloads_using_workload_analyzer.html"
    - title: Performance del carico di lavoro
      url: "/performance-checker/concept_collect_data_and_monitor_workload_performance.html"
    - title: Gestire le performance
      url: "/performance-checker/concept_manage_performance_using_perf_capacity_available_iops.html"
  - title: Monitoraggio dello storage e dello stato degli oggetti
    links:
    - title: Carichi di lavoro
      url: "/storage-mgmt/concept_provision_and_manage_workloads.html"
    - title: Infrastruttura virtuale
      url: "/storage-mgmt/concept_monitor_vmware_virtual_infrastructure.html"
    - title: Configurazioni MetroCluster
      url: "/storage-mgmt/concept_manage_and_monitor_metrocluster_configurations.html"
    - title: Integrità dei cluster e degli oggetti del cluster
      url: "/health-checker/concept_manage_and_monitor_clusters_and_cluster_object_health.html"
    - title: Soglie di integrità
      url: "/health-checker/concept_manage_health_thresholds.html"
    - title: Invia messaggi AutoSupport e pacchetti di supporto
      url: "/health-checker/task_send_asup_to_technical_support.html"
  - title: Monitoraggio della protezione dei dati
    links:
    - title: Impostare la relazione di protezione
      url: "/data-protection/task_set_up_protection_relationships_in_unified_manager.html"
    - title: Eseguire failover e failback
      url: "/data-protection/task_perform_protection_relationship_failover_and_failback.html"
    - title: Gestire la relazione di protezione
      url: "/data-protection/concept_manage_and_monitor_protection_relationships.html"
    - title: Monitorare le relazioni di disaster recovery
      url: "/data-protection/task_monitor_storage_vms_using_relationships_page.html"
    - title: Monitorare le configurazioni MetroCluster
      url: "/storage-mgmt/task_monitor_metrocluster_configurations.html"
    - title: Generare report
      url: "/reporting/concept_unified_manager_reporting.html"
  - title: Utilizzare API REST
    links:
    - title: Inizia subito
      url: "/api-automation/concept_api_url_and_categories.html"
    - title: Accedere alle API di Unified Manager
      url: "/api-automation/concept_rest_api_access_and_authentication_in_um_apis.html"
    - title: Gestire gli oggetti storage
      url: "/api-automation/concept_data_center_apis.html"
    - title: Accedere alle API di ONTAP
      url: "/api-automation/concept_gateway_apis.html"
    - title: Flussi di lavoro comuni
      url: "/api-automation/concept_workflow_intro.html"
    - title: Eseguire il provisioning dello storage
      url: "/api-automation/concept_provision_workflow.html"
    - title: Riferimento API per Unified Manager
      url: https://library.netapp.com/ecmdocs/ECMLP2885890/html/index.html
  - title: Eventi e avvisi
    links:
    - title: Dashboard
      url: "/storage-mgmt/reference_dashboard_page.html"
    - title: Workflow degli eventi
      url: "/events/concept_what_happens_when_an_event_is_received.html"
    - title: Eventi della piattaforma Active IQ
      url: "/events/concept_how_active_iq_platform_events_are_generated.html"
    - title: Eventi e tipi di severità
      url: "/events/reference_list_of_events_and_severity_types.html"
    - title: Eventi di correzione
      url: "/storage-mgmt/concept_fix_ontap_issues_directly_from_unified_manager.html"
    - title: Risoluzione automatica dei problemi
      url: "/storage-mgmt/reference_what_ontap_issues_can_unified_manager_fix.html"
  - title: Più risorse
    links:
    - title: Video di Unified Manager
      url: https://www.youtube.com/playlist?list=PLdXI3bZJEw7mp3jFSg0IJgo3oeDQRY-Gl
    - title: Blog di Unified Manager
      url: https://www.netapp.com/blog/#q=active%20iq%20unified%20manager&t=Blogs&sort=%40publish_date_mktg%20descending&layout=card&f:@facet_language_mktg=[English]
    - title: Documentazione per Active IQ Unified Manager 9.9 o versioni precedenti
      url: https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62791
