---
settings:
  name: Active IQ Unified Manager
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - version-number: '9.18'
    url: "/active-iq-unified-manager"
  - version-number: '9.16'
    url: "/active-iq-unified-manager-916"
  - version-number: '9.14'
    url: "/active-iq-unified-manager-914"
  - version-number: '9.13'
    url: "/active-iq-unified-manager-913"
  - version-number: '9.12'
    url: "/active-iq-unified-manager-912"
  - version-number: '9.11'
    url: "/active-iq-unified-manager-911"
  - version-number: '9.10'
    url: "/active-iq-unified-manager-910"
  langs: it-it,us-en,de-de,es-es,fr-fr,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentazione Active IQ Unified Manager 9.18
    url: "/index.html"
  - title: Note di rilascio
    url: "/reference_release_notes.html"
  - title: Inizia subito
    entries:
    - title: Installazione rapida per VMware vSphere
      url: "/install-vapp/qsg-vapp.html"
    - title: Installazione rapida per Linux
      url: "/install-linux/qsg-linux.html"
    - title: Installazione rapida per Windows
      url: "/install-windows/qsg-windows.html"
  - section: install-vapp
  - section: install-linux
  - section: install-windows
  - section: config
  - section: storage-mgmt
  - section: events
  - section: performance-checker
  - section: health-checker
  - section: data-protection
  - section: reporting
  - section: api-automation
  - title: Note legali
    url: "/legal-notices.html"
