---
permalink: api-automation/concept_get_started_with_um_apis.html 
sidebar: sidebar 
keywords: active iq, unified manager 
summary: 'Active IQ Unified Manager offre un set di API per gestire le risorse di storage sui sistemi di storage supportati attraverso un"interfaccia di servizio Web RESTful per qualsiasi integrazione di terze parti.' 
---
= Introduzione alle API REST di Active IQ Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager offre un set di API per gestire le risorse di storage sui sistemi di storage supportati attraverso un'interfaccia di servizio Web RESTful per qualsiasi integrazione di terze parti.

In questi argomenti, troverai informazioni sulle API di Unified Manager, flussi di lavoro di esempio per risolvere problemi specifici e alcuni codici di esempio. Utilizzando queste informazioni, è possibile creare client RESTful delle soluzioni software di gestione NetApp per la gestione dei sistemi NetApp. Le API sono basate sullo stile architettonico REST (Representational state Transfer). Sono supportate tutte e quattro le operazioni REST Create, Read, Update ed Delete (note anche come CRUD).
