---
permalink: api-automation/concept_administration_apis.html 
sidebar: sidebar 
keywords: perform, administrative, tasks 
summary: È possibile utilizzare le API nella categoria di amministrazione per modificare le impostazioni di backup, verificare le informazioni del file di backup e i certificati del cluster e gestire i cluster ONTAP come origini dati Active IQ Unified Manager. 
---
= Esecuzione di attività amministrative utilizzando le API
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare le API in `administration` Categoria per modificare le impostazioni di backup, verificare le informazioni del file di backup e i certificati del cluster e gestire i cluster ONTAP come origini dati Active IQ Unified Manager.

[NOTE]
====
Per eseguire queste operazioni, è necessario disporre del ruolo di amministratore dell'applicazione. È inoltre possibile utilizzare l'interfaccia utente Web di Unified Manager per configurare queste impostazioni.

====
[cols="3*"]
|===
| Verbo HTTP | Percorso | Descrizione 


 a| 
`GET`

`PATCH`
 a| 
`/admin/backup-settings`

`/admin/backup-settings`
 a| 
È possibile utilizzare `GET` Metodo per visualizzare le impostazioni della pianificazione di backup configurata in Unified Manager per impostazione predefinita. È possibile verificare quanto segue:

* Se la pianificazione è attivata o disattivata
* Frequenza del backup pianificato (giornaliero o settimanale)
* Ora del backup
* Numero massimo di file di backup da conservare nell'applicazione


L'ora del backup si trova nel fuso orario del server.

Le impostazioni di backup del database sono disponibili su Unified Manager per impostazione predefinita e non è possibile creare una pianificazione di backup. Tuttavia, è possibile utilizzare `PATCH` metodo per modificare le impostazioni predefinite.



 a| 
`GET`
 a| 
`/admin/backup-file-info`
 a| 
Ogni volta che viene modificata la pianificazione di backup per Unified Manager, viene generato un file dump di backup. È possibile utilizzare questo metodo per verificare se il file di backup viene generato in base alle impostazioni di backup modificate e se le informazioni sul file corrispondono alle impostazioni modificate.



 a| 
`GET`
 a| 
`/admin/datasource-certificate`
 a| 
È possibile utilizzare questo metodo per visualizzare il certificato dell'origine dati (cluster) dall'archivio trust. La convalida del certificato è necessaria prima di aggiungere un cluster ONTAP come origine dati di Unified Manager.



 a| 
`GET`

`POST`

`PATCH`

`DELETE`
 a| 
`/admin/datasources/clusters`

`/admin/datasources/clusters/\{key}`
 a| 
È possibile utilizzare `GET` Metodo per recuperare i dettagli delle origini dati (cluster ONTAP) gestite da Unified Manager.

È inoltre possibile aggiungere un nuovo cluster a Unified Manager come origine dati. Per aggiungere un cluster, è necessario conoscerne il nome host, il nome utente e la password.

Per modificare ed eliminare un cluster gestito come origine dati da Unified Manager, utilizzare la chiave cluster ONTAP.

|===