---
permalink: api-automation/concept_view_workloads.html 
sidebar: sidebar 
keywords: view, storage, workloads 
summary: 'Le API elencate di seguito consentono di visualizzare un elenco consolidato di carichi di lavoro dello storage per tutti i cluster ONTAP nel data center. Le API forniscono inoltre una vista riepilogativa del numero di carichi di lavoro dello storage forniti nell"ambiente Active IQ Unified Manager e delle relative statistiche di capacità e performance (IOPS).' 
---
= Visualizzazione dei carichi di lavoro dello storage mediante API
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le API elencate di seguito consentono di visualizzare un elenco consolidato di carichi di lavoro dello storage per tutti i cluster ONTAP nel data center. Le API forniscono inoltre una vista riepilogativa del numero di carichi di lavoro dello storage forniti nell'ambiente Active IQ Unified Manager e delle relative statistiche di capacità e performance (IOPS).



== Visualizza i carichi di lavoro dello storage

Puoi utilizzare il seguente metodo per visualizzare tutti i carichi di lavoro dello storage in tutti i cluster del tuo data center. Per informazioni sul filtraggio della risposta in base a colonne specifiche, consultare la documentazione di riferimento API disponibile nell'istanza di Unified Manager.

[cols="3*"]
|===
| Categoria | Verbo HTTP | Percorso 


 a| 
provider di storage
 a| 
OTTIENI
 a| 
`/storage-provider/workloads`

|===


== Visualizza il riepilogo dei carichi di lavoro dello storage

È possibile utilizzare il seguente metodo per valutare la capacità utilizzata, la capacità disponibile, gli IOPS utilizzati, gli IOPS disponibili e il numero di carichi di lavoro dello storage gestiti da ciascun livello di servizio delle performance. I carichi di lavoro dello storage visualizzati possono essere per qualsiasi condivisione LUN, file share NFS o CIFS. L'API offre una panoramica dei carichi di lavoro dello storage, una panoramica dei carichi di lavoro dello storage forniti da Unified Manager, una panoramica del data center, una panoramica dello spazio totale, utilizzato e disponibile e degli IOPS nel data center, in termini di livelli di Performance Service assegnati. Le informazioni ricevute in risposta a questa API vengono utilizzate per popolare la dashboard nell'interfaccia utente di Unified Manager.

[cols="3*"]
|===
| Categoria | Verbo HTTP | Percorso 


 a| 
provider di storage
 a| 
OTTIENI
 a| 
`/storage-provider/workloads-summary`

|===