---
permalink: api-automation/reference_recommendations_to_use_um_apis.html 
sidebar: sidebar 
keywords: recommendations, apis, active iq, unified, manager 
summary: Quando si utilizzano le API in Active IQ Unified Manager, è necessario seguire alcune procedure consigliate. 
---
= Raccomandazioni per l'utilizzo delle API per Active IQ Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si utilizzano le API in Active IQ Unified Manager, è necessario seguire alcune procedure consigliate.

* Per un'esecuzione valida, tutti i tipi di contenuto della risposta devono essere nel seguente formato:
+
[listing]
----
application/json
----
* Il numero di versione dell'API non è correlato al numero di versione del prodotto. Utilizzare la versione più recente dell'API disponibile per l'istanza di Unified Manager. Per ulteriori informazioni sulle versioni delle API di Unified Manager, vedere la sezione "`reversione delle API ST in Active IQ Unified Manager`".
* Durante l'aggiornamento dei valori degli array mediante un'API di Unified Manager, è necessario aggiornare l'intera stringa di valori. Non è possibile aggiungere valori a un array. È possibile sostituire solo un array esistente.
* È possibile utilizzare gli operatori di filtro, come pipe (|) e wild card (+*+) per tutti i parametri di query, ad eccezione dei valori doppi, ad esempio IOPS e performance nelle API delle metriche.
* Evitare di eseguire query sugli oggetti utilizzando una combinazione di wild card (+*+) e pipe (|) degli operatori di filtro. Potrebbe recuperare un numero di oggetti non corretto.
* Quando si utilizzano i valori per il filtro, assicurarsi che il valore non contenga alcun valore `?` carattere. In questo modo si riducono i rischi di SQL injection.
* Tenere presente che il `GET` (All) la richiesta per qualsiasi API restituisce un massimo di 1000 record. Anche se si esegue la query impostando `max_records` parametro con un valore superiore a 1000, vengono restituiti solo 1000 record.
* Per eseguire le funzioni amministrative, si consiglia di utilizzare l'interfaccia utente di Unified Manager.

