---
permalink: performance-checker/concept_navigate_performance_workflows_in_unified_manager_ui.html 
sidebar: sidebar 
keywords: navigating, performance, workflows, unified manager, gui 
summary: 'L"interfaccia di Unified Manager fornisce molte pagine per la raccolta e la visualizzazione delle informazioni sulle performance. Il pannello di navigazione sinistro consente di accedere alle pagine della GUI e di visualizzare e configurare le informazioni utilizzando le schede e i collegamenti presenti nelle pagine.' 
---
= Navigazione nei flussi di lavoro delle performance nella GUI di Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'interfaccia di Unified Manager fornisce molte pagine per la raccolta e la visualizzazione delle informazioni sulle performance. Il pannello di navigazione sinistro consente di accedere alle pagine della GUI e di visualizzare e configurare le informazioni utilizzando le schede e i collegamenti presenti nelle pagine.

Per monitorare e risolvere i problemi relativi alle prestazioni del cluster, utilizzare tutte le pagine seguenti:

* pagina del dashboard
* pagine di inventario degli oggetti di storage e di rete
* pagine dei dettagli dell'oggetto storage (incluso performance explorer)
* pagine di configurazione e configurazione
* pagine di eventi

