---
permalink: performance-checker/concept_how_enabling_flash_pool_can_improve_workload_performance.html 
sidebar: sidebar 
keywords: enable, flash pool, storage, aggregate, improve, workload, performance 
summary: Puoi migliorare le performance dei carichi di lavoro attivando la funzione Flash Pool su un aggregato. Un Flash Pool è un aggregato che incorpora sia HDD che SSD. Gli HDD vengono utilizzati per lo storage primario e gli SSD forniscono una cache di lettura e scrittura dalle performance elevate per migliorare le performance aggregate. 
---
= In che modo l'abilitazione di Flash Pool su un aggregato di storage può migliorare le performance dei carichi di lavoro
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi migliorare le performance dei carichi di lavoro attivando la funzione Flash Pool su un aggregato. Un Flash Pool è un aggregato che incorpora sia HDD che SSD. Gli HDD vengono utilizzati per lo storage primario e gli SSD forniscono una cache di lettura e scrittura dalle performance elevate per migliorare le performance aggregate.

In Unified Manager, la pagina Dettagli evento visualizza il nome dell'aggregato in conflitto. È possibile utilizzare Gestore di sistema di ONTAP o i comandi ONTAP per verificare se Flash Pool è attivato per un aggregato. Se si dispone di SSD installati, è possibile utilizzare l'interfaccia della riga di comando per attivarla. Se si dispone di SSD installati, è possibile eseguire il seguente comando sull'aggregato per verificare se Flash Pool è attivato: `*cluster::> storage aggregate show -aggregate aggr_name -field hybrid-enabled*`

In questo comando, `_aggr_name_` è il nome dell'aggregato, ad esempio l'aggregato in conflitto.

Per ulteriori informazioni su Flash Pool e sui requisiti per il suo utilizzo, consulta la _Guida alla gestione dello storage fisico Clustered Data ONTAP_.
