---
permalink: performance-checker/task_identify_shark_workloads_involved_in_performance_event.html 
sidebar: sidebar 
keywords: identify, shark workloads, involved, dynamic, performance, event 
summary: 'In Unified Manager, è possibile identificare i carichi di lavoro con la maggiore deviazione nell"utilizzo di un componente storage in conflitto. L"identificazione di questi workload consente di determinare se questi workload devono essere spostati in un cluster meno utilizzato.' 
---
= Identificazione dei carichi di lavoro di Shark coinvolti in un evento di performance dinamico
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In Unified Manager, è possibile identificare i carichi di lavoro con la maggiore deviazione nell'utilizzo di un componente storage in conflitto. L'identificazione di questi workload consente di determinare se questi workload devono essere spostati in un cluster meno utilizzato.

*Cosa ti serve*

* È necessario disporre del ruolo di operatore, amministratore dell'applicazione o amministratore dello storage.
* Esistono eventi dinamici di performance nuovi, riconosciuti o obsoleti.


Nella pagina Dettagli evento viene visualizzato un elenco dei carichi di lavoro definiti dall'utente e dal sistema, classificati in base all'utilizzo più elevato del componente o più interessati dall'evento. I valori si basano sui picchi identificati da Unified Manager al momento del rilevamento e dell'ultima analisi dell'evento.

.Fasi
. Visualizzare la pagina *Dettagli evento* per visualizzare le informazioni relative all'evento.
. Nei grafici Workload Latency (latenza del carico di lavoro) e Workload Activity (attività del carico di lavoro), selezionare *Shark workload*.
. Posizionare il cursore sui grafici per visualizzare i principali carichi di lavoro definiti dall'utente che influiscono sul componente e il nome del carico di lavoro di Shark.

