---
permalink: storage-mgmt/reference_issue_with_ldap_using_other_authentication_services.html 
sidebar: sidebar 
keywords: issue, addi, ldap, use, other, authentication, services 
summary: 'Risoluzione dei problemi: Problema con l"aggiunta di LDAP utilizzando altri servizi di autenticazione' 
---
= Problema con l'aggiunta di LDAP utilizzando altri servizi di autenticazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si seleziona altri come servizio di autenticazione, l'utente e il gruppo Object Class conservano i valori del modello precedentemente selezionato. Se il server LDAP non utilizza gli stessi valori, l'operazione potrebbe non riuscire.

*Causa*

Gli utenti non sono configurati correttamente in OpenLDAP.

*Azione correttiva*

È possibile risolvere manualmente questo problema utilizzando una delle seguenti soluzioni alternative.

Se la classe di oggetti utente LDAP e la classe di oggetti gruppo sono rispettivamente utente e gruppo, eseguire la seguente procedura:

. Nel riquadro di spostamento a sinistra, fare clic su**General** > *Remote Authentication*.
. Nel menu a discesa *Servizio di autenticazione*, selezionare *Active Directory*, quindi selezionare *altri*.
. Compilare i campi di testo.


Se la classe di oggetti utente LDAP e la classe di oggetti di gruppo sono rispettivamente positxAccount e positxGroup, attenersi alla seguente procedura:

. Nel riquadro di spostamento di sinistra, fare clic su **Generale** > *autenticazione remota*.
. Nel menu a discesa *Authentication Service*, selezionare *OpenLDAP*, quindi *altri*.
. Compilare i campi di testo.


Se le prime due soluzioni alternative non sono valide, chiamare il `option-set` API e impostare `auth.ldap.userObjectClass` e. `auth.ldap.groupObjectClass` opzioni per i valori corretti.
