---
permalink: storage-mgmt/task_view_user_and_user_group_quotas.html 
sidebar: sidebar 
keywords: view, user, user, group, quotas 
summary: 'La pagina Storage VM / Health Details (Dettagli stato/VM di storage) visualizza informazioni sulle quote utente e gruppo di utenti configurate sulla SVM. È possibile visualizzare il nome dell"utente o del gruppo di utenti, i limiti impostati su dischi e file, lo spazio su disco e file utilizzato e l"indirizzo e-mail per la notifica.' 
---
= Visualizzazione delle quote di utenti e gruppi di utenti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La pagina Storage VM / Health Details (Dettagli stato/VM di storage) visualizza informazioni sulle quote utente e gruppo di utenti configurate sulla SVM. È possibile visualizzare il nome dell'utente o del gruppo di utenti, i limiti impostati su dischi e file, lo spazio su disco e file utilizzato e l'indirizzo e-mail per la notifica.

*Cosa ti serve*

È necessario disporre del ruolo di operatore, amministratore dell'applicazione o amministratore dello storage.

.Fasi
. Nel riquadro di navigazione a sinistra, fare clic su *Storage* > *Storage VMS*.
. Nella vista *Health: All Storage VM*, selezionare una Storage VM, quindi fare clic sulla scheda *User and Group quote* (quote utente e gruppo).


*Informazioni correlate*

link:../config/task_add_users.html["Aggiunta di utenti"]
