---
permalink: storage-mgmt/task_add_space_to_data_directory_of_um_linux_host.html 
sidebar: sidebar 
keywords: add, space, data directory, linux host 
summary: 'Se è stato assegnato spazio su disco insufficiente a `/opt/netapp/data` Directory per supportare Unified Manager quando si configura originariamente l"host Linux e si installa Unified Manager, è possibile aggiungere spazio su disco dopo l"installazione aumentando lo spazio su disco su `/opt/netapp/data` directory.' 
---
= Aggiunta di spazio alla directory dei dati dell'host Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se è stato assegnato spazio su disco insufficiente a `/opt/netapp/data` Directory per supportare Unified Manager quando si configura originariamente l'host Linux e si installa Unified Manager, è possibile aggiungere spazio su disco dopo l'installazione aumentando lo spazio su disco su `/opt/netapp/data` directory.

.Prima di iniziare
È necessario disporre dell'accesso utente root alla macchina Red Hat Enterprise Linux su cui è installato Unified Manager.

Si consiglia di eseguire il backup del database di Unified Manager prima di aumentare le dimensioni della directory dei dati.

.Fasi
. Accedere come utente root alla macchina Linux su cui si desidera aggiungere spazio su disco.
. Arrestare il servizio Unified Manager e il software MySQL associato nell'ordine indicato: `systemctl stop ocieau ocie mysqld`
. Creare una cartella di backup temporanea (ad esempio, `/backup-data`) con spazio su disco sufficiente per contenere i dati nella corrente `/opt/netapp/data` directory.
. Copiare il contenuto e la configurazione dei privilegi dell'esistente `/opt/netapp/data` directory nella directory dei dati di backup:
+
`cp -arp /opt/netapp/data/* /backup-data`

. Se Linux è attivato:
+
.. Ottenere il tipo di se Linux per le cartelle esistenti `/opt/netapp/data` cartella:
+
`se_type=`ls -Z /opt/netapp/data| awk '{print $4}'| awk -F: '{print $3}'| head -1`

+
Il sistema restituisce una conferma simile a quanto segue:

+
[listing]
----
echo $se_type
mysqld_db_t
----
.. Eseguire `chcon` Per impostare il tipo di se Linux per la directory di backup:
+
`chcon -R --type=mysqld_db_t /backup-data`



. Rimuovere il contenuto di `/opt/netapp/data` directory:
+
.. `cd /opt/netapp/data`
.. `rm -rf *`


. Espandere le dimensioni di `/opt/netapp/data` Directory fino a un minimo di 150 GB tramite comandi LVM o aggiungendo dischi aggiuntivi.
+
[NOTE]
====
Se hai creato `/opt/netapp/data` da un disco, quindi non si dovrebbe provare a montare `/opt/netapp/data` Come condivisione NFS o CIFS. Perché, in questo caso, se si tenta di espandere lo spazio su disco, alcuni comandi LVM, ad esempio `resize` e. `extend` potrebbe non funzionare come previsto.

====
. Verificare che il `/opt/netapp/data` il proprietario della directory (mysql) e il gruppo (root) rimangono invariati:
+
`ls -ltr /opt/netapp/ | grep data`

+
Il sistema restituisce una conferma simile a quanto segue:

+
[listing]
----
drwxr-xr-x.  17 mysql root  4096 Aug 28 13:08 data
----
. Se Linux è attivato, verificare che il contesto per `/opt/netapp/data` la directory è ancora impostata su mysqld_db_t:
+
.. `touch /opt/netapp/data/abc`
.. `ls -Z /opt/netapp/data/abc`
+
Il sistema restituisce una conferma simile a quanto segue:

+
[listing]
----
-rw-r--r--. root root unconfined_u:object_r:mysqld_db_t:s0 /opt/netapp/data/abc
----


. Eliminare il file `abc` in modo che questo file estraneo non causi un errore di database in futuro.
. Copiare il contenuto da `backup-data` torna all'expanded `/opt/netapp/data` directory:
+
`cp -arp /backup-data/* /opt/netapp/data/`

. Se Linux è attivato, eseguire il seguente comando:
+
`chcon -R --type=mysqld_db_t /opt/netapp/data`

. Avviare il servizio MySQL:
+
`systemctl start mysqld`

. Una volta avviato il servizio MySQL, avviare i servizi ocie e ocieau nell'ordine indicato:
+
`systemctl start ocie ocieau`

. Una volta avviati tutti i servizi, eliminare la cartella di backup `/backup-data`:
+
`rm -rf /backup-data`


