---
permalink: storage-mgmt/task_remove_clusters.html 
sidebar: sidebar 
keywords: remove, cluster 
summary: È possibile rimuovere un cluster da Unified Manager utilizzando la pagina Cluster Setup. Ad esempio, è possibile rimuovere un cluster se il rilevamento del cluster non riesce o quando si desidera decommissionare un sistema storage. 
---
= Rimozione dei cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile rimuovere un cluster da Unified Manager utilizzando la pagina Cluster Setup. Ad esempio, è possibile rimuovere un cluster se il rilevamento del cluster non riesce o quando si desidera decommissionare un sistema storage.

*Cosa ti serve*

È necessario disporre del ruolo di amministratore dell'applicazione o di amministratore dello storage.

Questa attività rimuove il cluster selezionato da Unified Manager. Una volta rimosso, il cluster non viene più monitorato. Anche l'istanza di Unified Manager registrata con il cluster rimosso non viene registrata dal cluster.

La rimozione di un cluster elimina anche tutti gli oggetti di storage, i dati storici, i servizi di storage e tutti gli eventi associati da Unified Manager. Queste modifiche si riflettono sulle pagine di inventario e sui dettagli dopo il successivo ciclo di raccolta dei dati.

.Fasi
. Nel riquadro di navigazione a sinistra, fare clic su *Storage Management* > *Cluster Setup*.
. Nella pagina Cluster Setup, selezionare il cluster che si desidera rimuovere e fare clic su *Remove* (Rimuovi).
. Nella finestra di dialogo del messaggio *Remove Data Source* (Rimuovi origine dati), fare clic su *Remove* (Rimuovi) per confermare la richiesta di rimozione.


*Informazioni correlate*

link:../config/task_add_users.html["Aggiunta di utenti"]

link:../health-checker/task_view_cluster_list_and_details.html["Visualizzazione dell'elenco e dei dettagli del cluster"]
