---
permalink: storage-mgmt/task_create_rules_to_generate_email_addresses.html 
sidebar: sidebar 
keywords: create, rules, generate, email, addresses 
summary: 'È possibile creare regole per specificare l"indirizzo e-mail in base alla quota utente associata a cluster, storage virtual machine (SVM), volumi, qtree, utenti o gruppi di utenti. Quando si verifica una violazione delle quote, viene inviata una notifica all"indirizzo e-mail specificato.' 
---
= Crea regole per generare indirizzi email
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile creare regole per specificare l'indirizzo e-mail in base alla quota utente associata a cluster, storage virtual machine (SVM), volumi, qtree, utenti o gruppi di utenti. Quando si verifica una violazione delle quote, viene inviata una notifica all'indirizzo e-mail specificato.

.Prima di iniziare
* È necessario disporre del ruolo di amministratore dell'applicazione o di amministratore dello storage.
* È necessario aver esaminato le linee guida nella pagina regole per generare indirizzo email quota utente e gruppo.


È necessario definire le regole per gli indirizzi email di quota e inserirle nell'ordine in cui si desidera eseguirli. Ad esempio, se desideri utilizzare l'indirizzo e-mail abc@xyz.com per ricevere notifiche sulle violazioni delle quote per abc e utilizzare l'indirizzo e-mail dl-$GROUP@$DOMAIN per tutti gli altri gruppi, le regole devono essere elencate nel seguente ordine:

* Se ( $USER == 'abc' ) allora abc@xyz.com
* Se ( $GROUP == * ) allora dl-$GROUP@$DOMAIN


Se nessuno dei criteri per le regole specificate viene soddisfatto, viene utilizzata la regola predefinita:

SE (@_USER_OR_GROUP == * ), ALLORA IL DOMINIO DI UN UTENTE O DI UN GRUPPO

.Fasi
. Nel riquadro di navigazione a sinistra, fare clic su *Generale* > *regole email quota*.
. Inserire la regola in base ai criteri.
. Fare clic su *Validate* (convalida) per convalidare la sintassi della regola.
+
Se la sintassi della regola non è corretta, viene visualizzato un messaggio di errore. Correggere la sintassi e fare nuovamente clic su *Validate*.

. Fare clic su *Save* (Salva).
. Verificare che l'indirizzo e-mail creato sia visualizzato nella scheda *quote utente e gruppo* della pagina dei dettagli Storage *VM / Health*.

