---
permalink: storage-mgmt/task_view_list_of_monitored_clusters.html 
sidebar: sidebar 
keywords: view, list, monitored, clusters 
summary: 'È possibile utilizzare la pagina Cluster Setup per visualizzare l"inventario dei cluster. È possibile visualizzare i dettagli dei cluster, ad esempio il nome o l"indirizzo IP e lo stato della comunicazione.' 
---
= Visualizzazione dell'elenco dei cluster monitorati
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare la pagina Cluster Setup per visualizzare l'inventario dei cluster. È possibile visualizzare i dettagli dei cluster, ad esempio il nome o l'indirizzo IP e lo stato della comunicazione.

*Cosa ti serve*

È necessario disporre del ruolo di operatore, amministratore dell'applicazione o amministratore dello storage.

.Fase
. Nel riquadro di navigazione a sinistra, fare clic su *Storage Management* > *Cluster Setup*.
+
Vengono visualizzati tutti i cluster nell'ambiente di storage gestito da Unified Manager. L'elenco dei cluster viene ordinato in base alla colonna del livello di gravità dello stato di raccolta. È possibile fare clic sull'intestazione di una colonna per ordinare i cluster in base a colonne diverse.


