---
permalink: health-checker/concept_introduction_to_unified_manager_health_monitoring.html 
sidebar: sidebar 
keywords: introduction, active iq, unified manager, health, monitor 
summary: 'Active IQ Unified Manager (in precedenza Unified Manager di OnCommand) consente di monitorare un gran numero di sistemi che eseguono il software ONTAP attraverso un"interfaccia utente centralizzata. L"infrastruttura server di Unified Manager offre scalabilità, supportabilità e funzionalità avanzate di monitoraggio e notifica.' 
---
= Introduzione al monitoraggio dello stato di salute di Active IQ Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager (in precedenza Unified Manager di OnCommand) consente di monitorare un gran numero di sistemi che eseguono il software ONTAP attraverso un'interfaccia utente centralizzata. L'infrastruttura server di Unified Manager offre scalabilità, supportabilità e funzionalità avanzate di monitoraggio e notifica.

Le funzionalità chiave di Unified Manager includono il monitoraggio, gli avvisi, la gestione della disponibilità e della capacità dei cluster, la gestione delle funzionalità di protezione e il raggruppamento dei dati diagnostici e l'invio al supporto tecnico.

È possibile utilizzare Unified Manager per monitorare i cluster. Quando si verificano problemi nel cluster, Unified Manager notifica all'utente i dettagli di tali problemi attraverso gli eventi. Alcuni eventi forniscono anche un'azione correttiva che è possibile intraprendere per risolvere i problemi. È possibile configurare gli avvisi per gli eventi in modo che, quando si verificano problemi, si riceva una notifica tramite e-mail e trap SNMP.

È possibile utilizzare Unified Manager per gestire gli oggetti di storage nel proprio ambiente associandoli alle annotazioni. È possibile creare annotazioni personalizzate e associare dinamicamente cluster, storage virtual machine (SVM) e volumi con le annotazioni attraverso le regole.

È inoltre possibile pianificare i requisiti di storage degli oggetti cluster utilizzando le informazioni fornite nei grafici di capacità e integrità per il rispettivo oggetto cluster.



== Capacità fisica e logica

Unified Manager utilizza i concetti di spazio fisico e logico utilizzati per gli oggetti di storage ONTAP.

* Capacità fisica: Lo spazio fisico si riferisce ai blocchi fisici di storage utilizzati nel volume. La "capacità fisica utilizzata" è generalmente inferiore alla capacità logica utilizzata a causa della riduzione dei dati dalle funzionalità di efficienza dello storage (come deduplica e compressione).
* Capacità logica: Lo spazio logico si riferisce allo spazio utilizzabile (i blocchi logici) in un volume. Lo spazio logico si riferisce al modo in cui lo spazio teorico può essere utilizzato, senza tenere conto dei risultati della deduplica o della compressione. "Spazio logico utilizzato" è lo spazio fisico utilizzato e i risparmi derivanti dalle funzionalità di efficienza dello storage (come deduplica e compressione) configurate. Questa misurazione appare spesso più grande della capacità fisica utilizzata perché non riflette la compressione dei dati e altre riduzioni dello spazio fisico. Pertanto, la capacità logica totale potrebbe essere superiore allo spazio fornito.




== Unità di misura della capacità

Unified Manager calcola la capacità dello storage in base a unità binarie di 1024 (2^10^) byte. In ONTAP 9.10.0 e versioni precedenti, queste unità venivano visualizzate come KB, MB, GB, TB e PB. A partire da ONTAP 9.10.1, vengono visualizzati in Unified Manager come KiB, MiB, GiB, TIB e PIB.


NOTE: Le unità utilizzate per il throughput continuano a essere kilobyte per secondo (Kbps), Megabyte per secondo (Mbps), Gigabyte per secondo (Gbps) o terabyte per secondo (Tbps) e così via, per tutte le versioni di ONTAP.

[cols="4*"]
|===
| Unità di capacità visualizzata in Unified Manager per ONTAP 9.10.0 e versioni precedenti | Unità di capacità visualizzata in Unified Manager per ONTAP 9.10.1 | Calcolo | Valore in byte 


 a| 
KB
 a| 
KiB
 a| 
1024
 a| 
1024 byte



 a| 
MB
 a| 
MIB
 a| 
1024 * 1024
 a| 
1,048,576 byte



 a| 
GB
 a| 
Gib
 a| 
1024 * 1024 * 1024
 a| 
1,073,741,824 byte



 a| 
TB
 a| 
TIB
 a| 
1024 * 1024 * 1024 * 1024
 a| 
1,099,511,627,776 byte

|===