---
permalink: health-checker/concept_what_database_restore_is.html 
sidebar: sidebar 
keywords: unified manager, database, restore 
summary: 'Un ripristino del database MySQL è il processo di ripristino di un file di backup di Unified Manager esistente sullo stesso server o su un altro server Unified Manager. L"operazione di ripristino viene eseguita dalla console di manutenzione di Unified Manager.' 
---
= Che cos'è un ripristino del database
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un ripristino del database MySQL è il processo di ripristino di un file di backup di Unified Manager esistente sullo stesso server o su un altro server Unified Manager. L'operazione di ripristino viene eseguita dalla console di manutenzione di Unified Manager.

Se si esegue un'operazione di ripristino sullo stesso sistema (locale) e i file di backup vengono memorizzati in locale, è possibile eseguire l'opzione di ripristino utilizzando il percorso predefinito. Se si esegue un'operazione di ripristino su un sistema Unified Manager diverso (un sistema remoto), è necessario copiare il file di backup, o i file, dallo storage secondario al disco locale prima di eseguire l'opzione di ripristino.

Durante il processo di ripristino, l'utente viene disconnesso da Unified Manager. Una volta completato il processo di ripristino, è possibile accedere al sistema.

Se si sta ripristinando l'immagine di backup su un nuovo server, al termine dell'operazione di ripristino è necessario generare un nuovo certificato di protezione HTTPS e riavviare il server Unified Manager. Sarà inoltre necessario riconfigurare le impostazioni di autenticazione SAML, se necessarie, quando si ripristina l'immagine di backup su un nuovo server.

[NOTE]
====
I file di backup precedenti non possono essere utilizzati per ripristinare un'immagine dopo che Unified Manager è stato aggiornato a una versione più recente del software. Per risparmiare spazio, tutti i vecchi file di backup, ad eccezione del file più recente, vengono rimossi automaticamente quando si aggiorna Unified Manager.

====
*Informazioni correlate*

link:../config/task_generate_an_https_security_certificate_ocf.html["Generazione di un certificato di protezione HTTPS"]

link:../config/task_enable_saml_authentication_um.html["Attivazione dell'autenticazione SAML"]

link:../config/concept_authentication_with_active_directory_or_openldap.html["Autenticazione con Active Directory o OpenLDAP"]
