---
permalink: health-checker/concept_manage_backup_and_restore_operations.html 
sidebar: sidebar 
keywords: backup, types, manage, restore, operations 
summary: 'È possibile creare backup di Active IQ Unified Manager e utilizzare la funzione di ripristino per ripristinare il backup sullo stesso sistema (locale) o su un nuovo sistema (remoto) in caso di guasto del sistema o perdita di dati.' 
---
= Gestione delle operazioni di backup e ripristino
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile creare backup di Active IQ Unified Manager e utilizzare la funzione di ripristino per ripristinare il backup sullo stesso sistema (locale) o su un nuovo sistema (remoto) in caso di guasto del sistema o perdita di dati.

Esistono tre metodi di backup e ripristino a seconda del sistema operativo su cui è stato installato Unified Manager e in base al numero di cluster e nodi gestiti:

[cols="3*"]
|===
| Sistema operativo | Dimensione dell'implementazione | Metodo di backup consigliato 


 a| 
VMware vSphere
 a| 
Qualsiasi
 a| 
Snapshot VMware dell'appliance virtuale Unified Manager



.2+| Red Hat Enterprise Linux o CentOS Linux  a| 
Piccolo
 a| 
Dump del database MySQL di Unified Manager



 a| 
Grande
 a| 
NetApp Snapshot del database Unified Manager



.2+| Microsoft Windows  a| 
Piccolo
 a| 
Dump del database MySQL di Unified Manager



 a| 
Grande
 a| 
NetApp Snapshot del database Unified Manager con protocollo iSCSI

|===
Questi diversi metodi sono descritti nelle sezioni che seguono.
