---
permalink: health-checker/concept_configure_backup_for_linux.html 
sidebar: sidebar 
keywords: netapp, snapshot copy, copies, linux, operate, system, configure, backup 
summary: Se Active IQ Unified Manager è installato su una macchina Linux, puoi decidere di configurare il backup e il ripristino utilizzando NetApp Snapshots. 
---
= Configura il backup su Linux in Active IQ Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se Active IQ Unified Manager è installato su una macchina Linux, puoi decidere di configurare il backup e il ripristino utilizzando NetApp Snapshots.

Le copie Snapshot richiedono pochissimo tempo, in genere solo pochi minuti, e il database di Unified Manager viene bloccato per un periodo di tempo molto breve, pertanto l'installazione non è più disgregazione. L'immagine consuma uno spazio di storage minimo e comporta un overhead delle performance trascurabile, in quanto registra solo le modifiche apportate ai file dall'ultima copia Snapshot. Poiché Snapshot viene creato su un cluster ONTAP, è possibile sfruttare altre funzionalità NetApp, come SnapMirror, per creare una protezione secondaria, se necessario.

Prima di iniziare un'operazione di backup, Unified Manager esegue un controllo dell'integrità per verificare che il sistema di destinazione sia disponibile.

[NOTE]
====
* È possibile ripristinare una copia Snapshot solo sulla stessa versione di Active IQ Unified Manager.
+
Ad esempio, se hai creato un backup su Unified Manager 9.18, il backup può essere ripristinato solo sui sistemi Unified Manager 9.18.

* In caso di modifiche nella configurazione di Snapshot, lo snapshot potrebbe non essere valido.


====


[[configure-snapshot-copy-location-in-active-iq-unified-manager]]
== Configura la posizione della copia Snapshot in Active IQ Unified Manager

È possibile configurare il volume in cui memorizzare le copie Snapshot in uno dei cluster ONTAP utilizzando Gestore di sistema di ONTAP o l'interfaccia utente di ONTAP.

.Prima di iniziare
Il cluster, la VM di storage e il volume devono soddisfare i seguenti requisiti:

* Requisiti del cluster:
+
** È necessario installare ONTAP 9.3 o versione successiva
** Deve essere geograficamente vicino al server Unified Manager
** Può essere monitorato da Unified Manager, ma non è necessario


* Requisiti delle macchine virtuali per lo storage:
+
** Il nome e la mappatura dei nomi devono essere impostati per utilizzare "`Files`"
** Utenti locali creati per corrispondere agli utenti lato client
** Assicurarsi che sia selezionata l'opzione All Read/Write access (tutti gli accessi in lettura/scrittura
** Assicurarsi che l'opzione accesso superutente sia impostata su "`any`" nel criterio di esportazione
** NFS per NetApp Snapshot per Linux
** NFSv4 deve essere attivato sul server NFS e sul dominio ID NFSv4 specificato sulla macchina virtuale del client e dello storage
** Il volume deve avere una dimensione almeno doppia rispetto alla directory Unified Manager/OPT/netapp/dati
+
Utilizzare il comando du -sh /opt/netapp/data/ per controllare la dimensione corrente.



* Requisiti di volume:
+
** Il volume deve avere una dimensione almeno doppia rispetto alla directory di Unified Manager /opt/netapp/dati
** Lo stile di protezione deve essere impostato su UNIX
** Il criterio locale di snapshot deve essere disattivato
** La funzione di dimensionamento automatico del volume deve essere attivata
** Il livello di servizio delle performance deve essere impostato su una policy con IOPS elevati e bassa latenza, ad esempio "`Extreme`"




Per informazioni dettagliate sulla creazione del volume NFS, vedere https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_configure_NFSv4_in_Cluster-Mode["Come configurare NFSv4 in ONTAP 9"] e a. http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-nfsv3-cg/home.html["Guida rapida alla configurazione NFS di ONTAP 9"].



[[specify-the-destination-location-for-snapshot-copies-in-active-iq-unified-manager]]
== Specifica la posizione di destinazione per le copie Snapshot in Active IQ Unified Manager

È necessario configurare la posizione di destinazione per le copie Snapshot di Active IQ Unified Manager su un volume già configurato in uno dei cluster ONTAP. Per definire la posizione, utilizzare la console di manutenzione.

* È necessario disporre delle credenziali dell'utente root per l'host Linux su cui è installato Active IQ Unified Manager.
* Per accedere alla console di manutenzione del server Unified Manager, è necessario disporre di un ID utente e di una password autorizzati.
* È necessario disporre dell'indirizzo IP di Cluster Management, del nome della VM di storage, del nome del volume e del nome utente e della password del sistema di storage.
* È necessario aver montato il volume sull'host Active IQ Unified Manager e disporre del percorso di montaggio.


.Fasi
. Utilizzare Secure Shell per connettersi all'indirizzo IP o all'FQDN del sistema Active IQ Unified Manager.
. Accedere al sistema con il nome utente di manutenzione (umadmin) e la password.
. Immettere il comando `maintenance_console` E premere Invio.
. Nella console di manutenzione *Menu principale*, inserire il numero dell'opzione *Backup Restore*.
. Inserire il numero per *Configure NetApp Snapshot Backup*.
. Inserire il numero per configurare NFS.
. Esaminare le informazioni da fornire, quindi inserire il numero *Enter Backup Configuration Details* (Immetti dettagli configurazione backup).
. Per identificare il volume in cui verrà scritta l'istantanea, inserire l'indirizzo IP dell'interfaccia di gestione del cluster, il nome della VM di storage, il nome del volume, il nome del LUN, il nome utente e la password del sistema di storage e il percorso di montaggio.
. Verificare queste informazioni e immettere `y`.
+
Il sistema esegue le seguenti operazioni:

+
** Stabilisce la connessione al cluster
** Interrompe tutti i servizi
** Crea una nuova directory nel volume e copia i file di configurazione del database Active IQ Unified Manager
** Elimina i file da Active IQ Unified Manager e crea un collegamento simbolico alla nuova directory del database
** Riavvia tutti i servizi


. Uscire dalla console di manutenzione e avviare l'interfaccia di Active IQ Unified Manager per creare una pianificazione per la copia Snapshot, se non è già stata eseguita questa operazione.

