---
permalink: health-checker/task_restore_mysql_db_on_linux_or_centos.html 
sidebar: sidebar 
keywords: restore, linux system, mysql, database, backup 
summary: In caso di perdita o danneggiamento dei dati, è possibile ripristinare Unified Manager allo stato stabile precedente con una perdita minima di dati. È possibile ripristinare il database di Unified Manager su un sistema Red Hat Enterprise Linux o CentOS locale o remoto utilizzando la console di manutenzione di Unified Manager. 
---
= Ripristino di un backup del database MySQL su un sistema Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In caso di perdita o danneggiamento dei dati, è possibile ripristinare Unified Manager allo stato stabile precedente con una perdita minima di dati. È possibile ripristinare il database di Unified Manager su un sistema Red Hat Enterprise Linux o CentOS locale o remoto utilizzando la console di manutenzione di Unified Manager.

*Cosa ti serve*

* È necessario disporre delle credenziali dell'utente root per l'host Linux su cui è installato Unified Manager.
* Per accedere alla console di manutenzione del server Unified Manager, è necessario disporre di un ID utente e di una password autorizzati.
* È necessario aver copiato il file di backup di Unified Manager e il contenuto della directory del repository del database nel sistema su cui verrà eseguita l'operazione di ripristino.
+
Si consiglia di copiare il file di backup nella directory predefinita /`data/ocum`-backup. I file del repository del database devono essere copiati in /`database-dumps-repo` sotto la sottodirectory /`ocum-backup` directory.

* I file di backup devono essere di `.7z` tipo.


La funzionalità di ripristino è specifica della piattaforma e della versione. È possibile ripristinare un backup di Unified Manager solo sulla stessa versione di Unified Manager. È possibile ripristinare un file di backup Linux o un file di backup di un'appliance virtuale su un sistema Red Hat Enterprise Linux o CentOS.

[TIP]
====
Se il nome della cartella di backup contiene uno spazio, è necessario includere il percorso assoluto o relativo tra virgolette doppie.

====
.Fasi
. Se si esegue un ripristino su un nuovo server, dopo aver installato Unified Manager non avviare l'interfaccia utente né configurare cluster, utenti o impostazioni di autenticazione al termine dell'installazione. Il file di backup inserisce queste informazioni durante il processo di ripristino.
. Utilizzando Secure Shell, connettersi all'indirizzo IP o al nome di dominio completo del sistema Unified Manager.
. Accedere al sistema con il nome utente di manutenzione (umadmin) e la password.
. Immettere il comando `maintenance_console` E premere Invio.
. Nella console di manutenzione *Menu principale*, inserire il numero dell'opzione *Backup Restore*.
. Inserire il numero per il backup * Restore MySQL.
. Quando richiesto, immettere il percorso assoluto del file di backup.
+
[listing]
----
Bundle to restore from: /data/ocum-backup/UM_9.8.N151113.1348_backup_rhel_02-20-2020-04-45.7z
----
+
Una volta completata l'operazione di ripristino, è possibile accedere a Unified Manager.



Dopo aver ripristinato il backup, se il server OnCommand Workflow Automation non funziona, attenersi alla seguente procedura:

. Sul server Workflow Automation, modificare l'indirizzo IP del server Unified Manager in modo che punti alla macchina più recente.
. Nel server Unified Manager, reimpostare la password del database se l'acquisizione non riesce nel passaggio 1.

