---
permalink: health-checker/task_specify_destination_location_for_snapshot_backups.html 
sidebar: sidebar 
keywords: specify, destination location, snapshot copies, copy 
summary: È necessario configurare la posizione di destinazione per le copie Snapshot di Active IQ Unified Manager su un volume già configurato in uno dei cluster ONTAP. Per definire la posizione, utilizzare la console di manutenzione. 
---
= Specifica del percorso di destinazione per le copie Snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario configurare la posizione di destinazione per le copie Snapshot di Active IQ Unified Manager su un volume già configurato in uno dei cluster ONTAP. Per definire la posizione, utilizzare la console di manutenzione.

* È necessario disporre delle credenziali dell'utente root per l'host Linux su cui è installato Active IQ Unified Manager.
* Per accedere alla console di manutenzione del server Unified Manager, è necessario disporre di un ID utente e di una password autorizzati.
* È necessario disporre dell'indirizzo IP di Cluster Management, del nome della VM di storage, del nome del volume e del nome utente e della password del sistema di storage.
* È necessario aver montato il volume sull'host Active IQ Unified Manager e disporre del percorso di montaggio.


.Fasi
. Utilizzare Secure Shell per connettersi all'indirizzo IP o all'FQDN del sistema Active IQ Unified Manager.
. Accedere al sistema con il nome utente di manutenzione (umadmin) e la password.
. Immettere il comando `maintenance_console` E premere Invio.
. Nella console di manutenzione *Menu principale*, inserire il numero dell'opzione *Backup Restore*.
. Inserire il numero per *Configure NetApp Snapshot Backup*.
. Inserire il numero per configurare NFS.
. Esaminare le informazioni da fornire, quindi inserire il numero *Enter Backup Configuration Details* (Immetti dettagli configurazione backup).
. Per identificare il volume in cui verrà scritta l'istantanea, inserire l'indirizzo IP dell'interfaccia di gestione del cluster, il nome della VM di storage, il nome del volume, il nome del LUN, il nome utente e la password del sistema di storage e il percorso di montaggio.
. Verificare queste informazioni e immettere `y`.
+
Il sistema esegue le seguenti operazioni:

+
** Stabilisce la connessione al cluster
** Interrompe tutti i servizi
** Crea una nuova directory nel volume e copia i file di configurazione del database Active IQ Unified Manager
** Elimina i file da Active IQ Unified Manager e crea un collegamento simbolico alla nuova directory del database
** Riavvia tutti i servizi


. Uscire dalla console di manutenzione e avviare l'interfaccia di Active IQ Unified Manager per creare una pianificazione per la copia Snapshot, se non è già stata eseguita questa operazione.

