---
permalink: health-checker/task_resolve_volume_offline_issues.html 
sidebar: sidebar 
keywords: resolve, volume, offline issues 
summary: 'Questo flusso di lavoro fornisce un esempio di come è possibile valutare e risolvere un evento offline di un volume che Unified Manager potrebbe visualizzare nella pagina di inventario di Event Management. In questo scenario, l"amministratore utilizza Unified Manager per risolvere uno o più eventi offline di un volume.' 
---
= Risoluzione dei problemi di volume offline
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Questo flusso di lavoro fornisce un esempio di come è possibile valutare e risolvere un evento offline di un volume che Unified Manager potrebbe visualizzare nella pagina di inventario di Event Management. In questo scenario, l'amministratore utilizza Unified Manager per risolvere uno o più eventi offline di un volume.

*Cosa ti serve*

È necessario disporre del ruolo di operatore, amministratore dell'applicazione o amministratore dello storage.

I volumi potrebbero essere segnalati offline per diversi motivi:

* L'amministratore di SVM ha deliberatamente portato il volume offline.
* Il nodo del cluster di hosting del volume è inattivo e il failover dello storage verso il partner ha Pair ha si è guastato.
* La SVM (Storage Virtual Machine) di hosting del volume viene arrestata perché il nodo che ospita il volume root di tale SVM non è attivo.
* L'aggregato di hosting del volume è inattivo a causa di un guasto simultaneo di due dischi RAID.


Per confermare o eliminare una o più di queste possibilità, è possibile utilizzare la pagina dell'inventario di gestione degli eventi e le pagine dei dettagli di Cluster/Health, Storage VM/Health e Volume/Health.

.Fasi
. Nel riquadro di spostamento di sinistra, fare clic su *Gestione eventi*.
. Nella pagina di inventario *Gestione eventi*, selezionare *Eventi disponibilità attivi*.
. Fare clic sul collegamento ipertestuale visualizzato per l'evento Volume Offline.
+
Viene visualizzata la pagina Dettagli evento per l'incidente di disponibilità.

. In questa pagina, consultare le note per verificare se l'amministratore di SVM ha portato il volume in questione offline.
. Nella pagina dei dettagli *evento*, è possibile esaminare le informazioni relative a una o più delle seguenti attività:
+
** Esaminare le informazioni visualizzate nel campo cause per ottenere una possibile guida diagnostica.
+
In questo esempio, le informazioni nel campo cause informano solo che il volume non è in linea.

** Controllare l'area Note e aggiornamenti per verificare se l'amministratore di SVM ha deliberatamente portato il volume in questione offline.
** Fare clic sull'origine dell'evento, in questo caso il volume riportato offline, per ottenere ulteriori informazioni su tale volume.
** Assegnare l'evento a un amministratore.
** Riconoscere l'evento o, se necessario, contrassegnarlo come risolto.



