---
permalink: health-checker/task_edit_group_actions.html 
sidebar: sidebar 
keywords: edit, group actions 
summary: 'È possibile modificare i parametri delle azioni di gruppo configurati in Unified Manager, ad esempio il nome dell"azione di gruppo, la descrizione, il nome del gruppo associato e i parametri del tipo di azione.' 
---
= Modifica delle azioni di gruppo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile modificare i parametri delle azioni di gruppo configurati in Unified Manager, ad esempio il nome dell'azione di gruppo, la descrizione, il nome del gruppo associato e i parametri del tipo di azione.

*Cosa ti serve*

È necessario disporre del ruolo di amministratore dell'applicazione o di amministratore dello storage.

.Fasi
. Nel riquadro di navigazione a sinistra, fare clic su *Storage Management* > *Groups*.
. Nella scheda *azioni gruppo*, selezionare l'azione di gruppo che si desidera modificare, quindi fare clic su *Modifica*.
. Nella finestra di dialogo *Modifica azione gruppo*, modificare il nome dell'azione di gruppo, la descrizione, il nome del gruppo associato e i parametri del tipo di azione, come richiesto.
. Fare clic su *Save* (Salva).

