---
permalink: health-checker/task_add_group_actions.html 
sidebar: sidebar 
keywords: add, group, actions 
summary: È possibile configurare le azioni di gruppo che si desidera applicare agli oggetti di storage di un gruppo. La configurazione delle azioni per un gruppo consente di risparmiare tempo, poiché non è necessario aggiungere queste azioni a ciascun oggetto singolarmente. 
---
= Aggiunta di azioni di gruppo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile configurare le azioni di gruppo che si desidera applicare agli oggetti di storage di un gruppo. La configurazione delle azioni per un gruppo consente di risparmiare tempo, poiché non è necessario aggiungere queste azioni a ciascun oggetto singolarmente.

*Cosa ti serve*

È necessario disporre del ruolo di amministratore dell'applicazione o di amministratore dello storage.

.Fasi
. Nel riquadro di navigazione a sinistra, fare clic su *Storage Management* > *Groups*.
. Nella scheda *azioni gruppo*, fare clic su *Aggiungi*.
. Nella finestra di dialogo *Aggiungi azione gruppo*, immettere un nome e una descrizione per l'azione.
. Dal menu *Gruppo*, selezionare un gruppo per il quale si desidera configurare l'azione.
. Dal menu *Action Type*, selezionare un tipo di azione.
+
La finestra di dialogo si espande, consentendo di configurare il tipo di azione selezionato con i parametri richiesti.

. Immettere i valori appropriati per i parametri richiesti per configurare un'azione di gruppo.
. Fare clic su *Aggiungi*.

