---
permalink: health-checker/task_determine_if_volume_is_offline_because_of_broken_disks.html 
sidebar: sidebar 
keywords: determine, volume, offline, broken disks, aggregate 
summary: 'È possibile utilizzare l"interfaccia utente Web di Unified Manager per confermare o eliminare la possibilità che un volume sia offline perché i problemi del disco RAID hanno portato l"aggregato host offline.' 
---
= Determinare se un volume è offline a causa di dischi rotti in un aggregato
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare l'interfaccia utente Web di Unified Manager per confermare o eliminare la possibilità che un volume sia offline perché i problemi del disco RAID hanno portato l'aggregato host offline.

*Cosa ti serve*

È necessario disporre del ruolo di operatore, amministratore dell'applicazione o amministratore dello storage.

Per determinare se la condizione di volume offline è causata da problemi del disco RAID che stanno portando l'aggregato di hosting offline, eseguire le seguenti operazioni:

.Fasi
. Individuare e fare clic sul collegamento ipertestuale visualizzato sotto aggregato nel riquadro *Related Devices* (dispositivi correlati) della pagina dei dettagli *Volume / Health*.
+
La pagina aggregato/Dettagli salute visualizza lo stato online o offline dell'aggregato di hosting. Se lo stato aggregato è online, i problemi del disco RAID non sono la causa della offline del volume.

. Se lo stato aggregato non è in linea, fare clic su *Disk Information* (informazioni disco) e cercare gli eventi del disco guasti nell'elenco *Events* (Eventi) nella scheda *Disk Information* (informazioni disco).
. Per identificare ulteriormente i dischi rotti, fare clic sul collegamento ipertestuale visualizzato sotto nodo nel riquadro *dispositivi correlati*.
+
Viene visualizzata la pagina Cluster / Health details (Dettagli cluster / stato).

. Fare clic su *Disks*, quindi selezionare *Broken* nel pannello *Filters* per visualizzare tutti i dischi in stato di rottura.
+
Se i dischi in stato interrotto hanno causato lo stato offline dell'aggregato host, il nome dell'aggregato viene visualizzato nella colonna aggregato interessato.



Dopo aver confermato che la condizione di volume offline è causata da dischi RAID rotti e dal conseguente aggregato di host offline, contattare l'amministratore o l'operatore appropriato per sostituire manualmente i dischi rotti e riportare l'aggregato online.
