---
permalink: health-checker/task_generate_hardware_inventory_report_for_contract_renewal.html 
sidebar: sidebar 
keywords: contract, renewal, cluster, inventory report, hardware, generate 
summary: 'È possibile generare un report che contiene un elenco completo di informazioni su cluster e nodi, ad esempio numeri di modello e di serie dell"hardware, tipi di dischi e conteggi, licenze installate e altro ancora. Questo report è utile per il rinnovo del contratto all"interno di siti sicuri (siti "oscuri") non connessi alla piattaforma NetAppActive IQ.' 
---
= Generazione di un report sull'inventario hardware per il rinnovo del contratto
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile generare un report che contiene un elenco completo di informazioni su cluster e nodi, ad esempio numeri di modello e di serie dell'hardware, tipi di dischi e conteggi, licenze installate e altro ancora. Questo report è utile per il rinnovo del contratto all'interno di siti sicuri ("siti `dARK`") non connessi alla piattaforma NetAppActive IQ.

*Cosa ti serve*

È necessario disporre del ruolo di operatore, amministratore dell'applicazione o amministratore dello storage.

.Fasi
. Nel riquadro di navigazione a sinistra, fare clic su *Storage* > *Nodes*.
. Accedere alla vista *Health: All Nodes* (Salute: Tutti i nodi) o *Performance: All Nodes* (prestazioni: Tutti i nodi).
. Selezionare *Report* > *** > **Report inventario hardware*.
+
Il report dell'inventario hardware viene scaricato come file .csv con informazioni complete alla data corrente.

. Fornisci queste informazioni al tuo contatto del supporto NetApp per il rinnovo del contratto.

