---
permalink: health-checker/task_configure_global_health_threshold_settings.html 
sidebar: sidebar 
keywords: configure, global health, threshold settings 
summary: È possibile configurare le condizioni delle soglie di integrità globali per capacità, crescita, Snapshot Reserve, quote e inode per monitorare in modo efficace le dimensioni di aggregato, volume e qtree. È inoltre possibile modificare le impostazioni per la generazione di eventi per il superamento delle soglie di ritardo. 
---
= Configurazione delle impostazioni della soglia di integrità globale
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile configurare le condizioni delle soglie di integrità globali per capacità, crescita, Snapshot Reserve, quote e inode per monitorare in modo efficace le dimensioni di aggregato, volume e qtree. È inoltre possibile modificare le impostazioni per la generazione di eventi per il superamento delle soglie di ritardo.

Le impostazioni della soglia di integrità globale si applicano a tutti gli oggetti a cui sono associati, ad esempio aggregati, volumi e così via. Quando vengono superate le soglie, viene generato un evento e, se sono configurati avvisi, viene inviata una notifica di avviso. Le soglie predefinite sono impostate sui valori consigliati, ma è possibile modificarle in modo da generare eventi a intervalli per soddisfare le esigenze specifiche. Quando le soglie vengono modificate, gli eventi vengono generati o resi obsoleti nel ciclo di monitoraggio successivo.

È possibile accedere alle impostazioni della soglia di integrità globale dalla sezione soglie evento del menu di navigazione a sinistra. È inoltre possibile modificare le impostazioni di soglia per singoli oggetti, dalla pagina di inventario o dalla pagina dei dettagli dell'oggetto.

* Per ulteriori informazioni, vedere link:task_configure_global_aggregate_health_threshold_values.html["Configurazione dei valori globali di soglia di integrità degli aggregati"].
+
È possibile configurare le impostazioni della soglia di integrità per capacità, crescita e copie Snapshot per tutti gli aggregati per tenere traccia di qualsiasi violazione di soglia.

* Per ulteriori informazioni, vedere link:task_configure_global_volume_health_threshold_values.html["Configurazione dei valori delle soglie globali di integrità del volume"].
+
È possibile modificare le impostazioni della soglia di integrità per capacità, copie Snapshot, quote qtree, crescita del volume, spazio di riserva di sovrascrittura, e inode per tutti i volumi per tenere traccia di qualsiasi violazione di soglia.

* Per ulteriori informazioni, vedere link:task_configure_global_qtree_health_threshold_values.html["Configurazione dei valori globali delle soglie di integrità del qtree"].
+
È possibile modificare le impostazioni della soglia di integrità per la capacità di tutti i qtree per tenere traccia di qualsiasi violazione di soglia.

* Per ulteriori informazioni, vedere link:task_configure_lag_threshold_settings_for_unmanaged_protection.html["Modifica delle impostazioni della soglia di integrità del ritardo per le relazioni di protezione non gestite"].
+
È possibile aumentare o ridurre la percentuale di tempo di avviso o ritardo degli errori in modo che gli eventi vengano generati a intervalli più adatti alle proprie esigenze.


