---
permalink: health-checker/task_generate_and_upload_support_bundle.html 
sidebar: sidebar 
keywords: generate, upload, support bundle 
summary: È possibile generare un pacchetto di supporto contenente informazioni diagnostiche, in modo da inviarlo al supporto tecnico per la risoluzione dei problemi. È inoltre possibile caricare il pacchetto di supporto su NetApp dalla console di manutenzione. 
---
= Generazione e caricamento di un bundle di supporto
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile generare un pacchetto di supporto contenente informazioni diagnostiche, in modo da inviarlo al supporto tecnico per la risoluzione dei problemi.

A partire da Unified Manager 9.8, se il server Unified Manager è connesso a Internet, è anche possibile caricare il pacchetto di supporto a NetApp dalla console di manutenzione.

*Cosa ti serve*

È necessario avere accesso alla console di manutenzione come utente di manutenzione.

Poiché alcuni tipi di dati di supporto possono utilizzare una grande quantità di risorse del cluster o richiedere molto tempo per il completamento, quando si seleziona il bundle di supporto completo è possibile specificare i tipi di dati da includere o escludere per ridurre le dimensioni del bundle di supporto. È inoltre possibile creare un bundle di supporto leggero che contiene solo 30 giorni di registri e record del database di configurazione, escludendo i dati sulle performance, i file di registrazione dell'acquisizione e il dump dell'heap del server.

Unified Manager memorizza solo i due pacchetti di supporto generati più di recente. I pacchetti di supporto meno recenti vengono eliminati dal sistema.

.Fasi
. Nella console di manutenzione *Menu principale*, selezionare *supporto/Diagnostica*.
. Selezionare *generate Light Support Bundle* o *generate Support Bundle* a seconda del livello di dettagli che si desidera includere nel pacchetto di supporto.
. Se si sceglie il bundle di supporto completo, selezionare o deselezionare i seguenti tipi di dati da includere o escludere nel bundle di supporto:
+
** *dump del database*
+
Un dump del database MySQL Server.

** *heap dump*
+
Un'istantanea dello stato dei principali processi del server Unified Manager. Questa opzione è disattivata per impostazione predefinita e deve essere selezionata solo quando richiesto dall'assistenza clienti.

** *registrazioni di acquisizione*
+
Registrazione di tutte le comunicazioni tra Unified Manager e i cluster monitorati.



+
[NOTE]
====
Se si deselezionano tutti i tipi di dati, il bundle di supporto viene ancora generato con altri dati di Unified Manager.

====
. Tipo `g`, Quindi premere Invio per generare il bundle di supporto.
+
Poiché la generazione di un bundle di supporto è un'operazione che richiede un uso intensivo della memoria, viene richiesto di verificare di voler generare il bundle di supporto in questo momento.

. Tipo `y`, Quindi premere Invio per generare il bundle di supporto.
+
Se non si desidera generare il bundle di supporto in questo momento, digitare `n`, Quindi premere Invio.

. Se sono stati inclusi i file dump del database nel bundle di supporto completo, viene richiesto di specificare il periodo di tempo per il quale si desidera includere le statistiche delle performance. L'inclusione delle statistiche sulle performance può richiedere molto tempo e spazio, per cui è possibile eseguire il dump del database senza includere statistiche sulle performance:
+
.. Inserire la data di inizio nel formato AAAAMMGG.
+
Ad esempio, immettere `20210101` Per il 1° gennaio 2021. Invio `n` se non si desidera includere le statistiche delle performance.

.. Inserire il numero di giorni di statistiche da includere, a partire dalle 12 alla data di inizio specificata.
+
È possibile immettere un numero compreso tra 1 e 10.



+
Se si includono le statistiche delle performance, il sistema visualizza il periodo di tempo per il quale verranno raccolte le statistiche delle performance.

. Una volta creato il pacchetto di supporto, viene richiesto se si desidera caricarlo su NetApp. Tipo `y`, Quindi premere Invio.
+
Viene richiesto di inserire il numero del caso di supporto.

. Se si dispone già di un numero di caso, immetterlo e premere Invio. In caso contrario, premere Invio.
+
Il bundle di supporto viene caricato in NetApp.



Se il server Unified Manager non è connesso a Internet o non è possibile caricare il bundle di supporto per qualsiasi altro motivo, è possibile recuperarlo e inviarlo manualmente. È possibile recuperarlo utilizzando un client SFTP o i comandi CLI UNIX o Linux. Nelle installazioni Windows è possibile utilizzare Desktop remoto (RDP) per recuperare il bundle di supporto.

Il bundle di supporto generato si trova nella directory /support sui sistemi VMware, in /opt/netapp/data/support/ sui sistemi Linux e in ProgramData/NetApp/OnCommandAppData/ocum/support sui sistemi Windows.

*Informazioni correlate*

link:../config/reference_unified_manager_roles_and_capabilities.html["Ruoli e funzionalità degli utenti di Unified Manager"]
