---
permalink: health-checker/task_view_all_security_events.html 
sidebar: sidebar 
keywords: view, active, security events 
summary: È possibile visualizzare tutti gli eventi di protezione attivi e assegnarli a un utente in grado di risolvere il problema. Inoltre, se alcuni eventi di protezione non si desidera ricevere, questo elenco può aiutare a identificare gli eventi che si desidera disattivare. 
---
= Visualizzazione di tutti gli eventi di sicurezza attivi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile visualizzare tutti gli eventi di protezione attivi e assegnarli a un utente in grado di risolvere il problema. Inoltre, se alcuni eventi di protezione non si desidera ricevere, questo elenco può aiutare a identificare gli eventi che si desidera disattivare.

*Cosa ti serve*

È necessario disporre del ruolo di operatore, amministratore dell'applicazione o amministratore dello storage.

.Fasi
. Nel riquadro di spostamento di sinistra, fare clic su *Gestione eventi*.
+
Per impostazione predefinita, gli eventi nuovi e confermati vengono visualizzati nella pagina di inventario Gestione eventi.

. Dal menu View (Visualizza), selezionare *Active Security events* (Eventi di sicurezza attivi).
+
La pagina visualizza tutti gli eventi New e Acknowledged Security generati negli ultimi 7 giorni.


