---
permalink: health-checker/task_configure_global_aggregate_health_threshold_values.html 
sidebar: sidebar 
keywords: configure, global, aggregate, health, threshold values 
summary: È possibile configurare i valori delle soglie globali di integrità per tutti gli aggregati per tenere traccia di qualsiasi violazione di soglia. Gli eventi appropriati vengono generati per le violazioni di soglia ed è possibile adottare misure preventive in base a tali eventi. È possibile configurare i valori globali in base alle impostazioni delle Best practice per le soglie applicabili a tutti gli aggregati monitorati. 
---
= Configurazione dei valori globali di soglia di integrità degli aggregati
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile configurare i valori delle soglie globali di integrità per tutti gli aggregati per tenere traccia di qualsiasi violazione di soglia. Gli eventi appropriati vengono generati per le violazioni di soglia ed è possibile adottare misure preventive in base a tali eventi. È possibile configurare i valori globali in base alle impostazioni delle Best practice per le soglie applicabili a tutti gli aggregati monitorati.

*Cosa ti serve*

È necessario disporre del ruolo di amministratore dell'applicazione o di amministratore dello storage.

Quando si configurano le opzioni a livello globale, i valori predefiniti degli oggetti vengono modificati. Tuttavia, se i valori predefiniti sono stati modificati a livello di oggetto, i valori globali non vengono modificati.

Le opzioni di soglia hanno valori predefiniti per un migliore monitoraggio, tuttavia è possibile modificare i valori in base ai requisiti dell'ambiente.

Quando la funzione di crescita automatica è attivata sui volumi che risiedono nell'aggregato, le soglie della capacità aggregata vengono considerate violate in base alle dimensioni massime del volume impostate dalla funzione di crescita automatica, non in base alle dimensioni originali del volume.

[NOTE]
====
I valori della soglia di integrità non sono applicabili all'aggregato root del nodo.

====
.Fasi
. Nel riquadro di navigazione a sinistra, fare clic su *soglie evento* > *aggregato*.
. Configurare i valori di soglia appropriati per capacità, crescita e copie Snapshot.
. Fare clic su *Save* (Salva).


*Informazioni correlate*

link:../config/task_add_users.html["Aggiunta di utenti"]
