---
permalink: health-checker/task_delete_groups.html 
sidebar: sidebar 
keywords: delete, groups 
summary: È possibile eliminare un gruppo da Unified Manager quando il gruppo non è più necessario. 
---
= Eliminazione di gruppi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eliminare un gruppo da Unified Manager quando il gruppo non è più necessario.

*Cosa ti serve*

* Nessuno degli oggetti storage (cluster, SVM o volumi) deve essere associato a qualsiasi regola di gruppo associata al gruppo che si desidera eliminare.
* È necessario disporre del ruolo di amministratore dell'applicazione o di amministratore dello storage.


.Fasi
. Nel riquadro di navigazione a sinistra, fare clic su *Storage Management* > *Groups*.
. Nella scheda *gruppi*, selezionare il gruppo che si desidera eliminare, quindi fare clic su *Elimina*.
. Nella finestra di dialogo *Avviso*, confermare l'eliminazione facendo clic su *Sì*.
+
L'eliminazione di un gruppo non elimina le azioni di gruppo associate al gruppo. Tuttavia, queste azioni di gruppo non verranno mappate dopo l'eliminazione del gruppo.


