---
permalink: health-checker/task_restore_snapshot_backup.html 
sidebar: sidebar 
keywords: restore, unified manager, snapshot copy, copies, 
summary: In caso di perdita o danneggiamento dei dati, è possibile ripristinare Unified Manager allo stato stabile precedente con una perdita minima di dati. È possibile ripristinare il database Snapshot di Unified Manager su un sistema operativo locale o remoto utilizzando la console di manutenzione di Unified Manager. 
---
= Ripristino di Unified Manager utilizzando le copie Snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In caso di perdita o danneggiamento dei dati, è possibile ripristinare Unified Manager allo stato stabile precedente con una perdita minima di dati. È possibile ripristinare il database Snapshot di Unified Manager su un sistema operativo locale o remoto utilizzando la console di manutenzione di Unified Manager.

*Cosa ti serve*

* È necessario disporre delle credenziali dell'utente root per l'host Linux e dei privilegi amministrativi per il computer host Windows su cui è installato Unified Manager.
* Per accedere alla console di manutenzione del server Unified Manager, è necessario disporre di un ID utente e di una password autorizzati.


La funzionalità di ripristino è specifica della piattaforma e della versione. È possibile ripristinare un backup di Unified Manager solo sulla stessa versione di Unified Manager.

.Fasi
. Connettersi all'indirizzo IP o al nome di dominio completo del sistema Unified Manager.
+
** Linux: Shell sicura
** Windows: Power Shell


. Accedere al sistema con le credenziali dell'utente root.
. Immettere il comando `maintenance_console` E premere Invio.
. Nella console di manutenzione *Menu principale*, inserire 4 per l'opzione *Backup Restore*.
. Inserire 2 per selezionare *Backup e ripristino utilizzando NetApp Snapshot*.
+
Se si esegue un ripristino su un nuovo server, dopo aver installato Unified Manager non avviare l'interfaccia utente né configurare cluster, utenti o impostazioni di autenticazione al termine dell'installazione. Inserire 1 per selezionare *Configure NetApp Snapshot Backup* e configurare le impostazioni per le copie Snapshot così come si trovano sul sistema originale.

. Inserire 3 per selezionare *Restore using NetApp Snapshot* (Ripristina con NetApp Snapshot*).
. Selezionare la copia Snapshot da cui si desidera ripristinare Unified Manager. Premere *Invio*.
. Una volta completato il processo di ripristino, accedere all'interfaccia utente di Unified Manager.


Dopo aver ripristinato il backup, se il server Workflow Automation non funziona, attenersi alla seguente procedura:

. Sul server Workflow Automation, modificare l'indirizzo IP del server Unified Manager in modo che punti alla macchina più recente.
. Nel server Unified Manager, reimpostare la password del database se l'acquisizione non riesce nel passaggio 1.

