---
permalink: health-checker/task_view_svm_list_and_details.html 
sidebar: sidebar 
keywords: view, storage vm list, details 
summary: 'Dalla vista Health: All Storage VM (Salute: Tutte le macchine virtuali dello storage), è possibile monitorare l"inventario delle macchine virtuali dello storage (SVM). È possibile utilizzare la pagina Storage VM / Health Details per visualizzare informazioni dettagliate sulle SVM monitorate.' 
---
= Visualizzazione dell'elenco e dei dettagli di Storage VM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dalla vista Health: All Storage VM (Salute: Tutte le macchine virtuali dello storage), è possibile monitorare l'inventario delle macchine virtuali dello storage (SVM). È possibile utilizzare la pagina Storage VM / Health Details per visualizzare informazioni dettagliate sulle SVM monitorate.

.Prima di iniziare
È necessario disporre del ruolo di operatore, amministratore dell'applicazione o amministratore dello storage.

È possibile visualizzare i dettagli di SVM, ad esempio la capacità, l'efficienza e la configurazione di una SVM. È inoltre possibile visualizzare informazioni sui dispositivi correlati e sugli avvisi correlati per la SVM.

.Fasi
. Nel riquadro di navigazione a sinistra, fare clic su *Storage* > *Storage VMS*.
. Scegliere uno dei seguenti modi per visualizzare i dettagli SVM:
+
** Per visualizzare le informazioni sullo stato di tutte le SVM in tutti i cluster, nel menu View (Visualizza), selezionare Health: All Storage VMS view (Stato: Vista di tutte le VM di storage).
** Per visualizzare i dettagli completi, fare clic sul nome della Storage VM.
+
È inoltre possibile visualizzare i dettagli completi facendo clic su *View Details* (Visualizza dettagli) nella finestra di dialogo Minimal Details (Dettagli minimi).



. Visualizzare gli oggetti correlati alla SVM facendo clic su *Visualizza correlati* nella finestra di dialogo Dettagli minimi.


*Informazioni correlate*

* link:../health-checker/reference_health_svm_details_page.html["Storage VM: Pagina dei dettagli sullo stato di salute"]
* link:../performance-checker/performance-view-all.html#performance-all-storage-vms-view["Performance: Vista di tutte le VM di storage"]
* link:../health-checker/task_view_antiransomware_status_of_all_volumes_storage_vms.html#view-security-details-of-all-volumes-with-anti-ransomware-detection["Sicurezza: Vista anti-ransomware"]
* link:../health-checker/task_view_detailed_security_status_for_clusters_and_svms.html["Visualizzazione dello stato di sicurezza per cluster e VM di storage"]
* link:../data-protection/reference_relationship_all_relationships_view.html["Relazione: Vista tutte le relazioni"]

