---
permalink: health-checker/task_view_fabricpool_capacity_information.html 
sidebar: sidebar 
keywords: view, fabricPool, cloud tier, mirror tier, capacity, information 
summary: 'È possibile visualizzare le informazioni sulla capacità di FabricPool per cluster, aggregati e volumi nelle pagine dell"inventario capacità e performance e dei dettagli per questi oggetti. Queste pagine visualizzano anche le informazioni del mirror FabricPool quando è stato configurato un Tier mirror.' 
---
= Visualizzazione delle informazioni sulla capacità FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile visualizzare le informazioni sulla capacità di FabricPool per cluster, aggregati e volumi nelle pagine dell'inventario capacità e performance e dei dettagli per questi oggetti. Queste pagine visualizzano anche le informazioni del mirror FabricPool quando è stato configurato un Tier mirror.

In queste pagine vengono visualizzate informazioni quali la capacità disponibile sul Tier di performance locale e sul Tier cloud, la capacità utilizzata in entrambi i Tier, gli aggregati collegati a un Tier cloud, E quali volumi stanno implementando le funzionalità di FabricPool spostando determinate informazioni nel Tier cloud.

Quando un livello cloud viene mirrorato su un altro provider cloud (il "`mlivello di orrore`"), entrambi i livelli cloud vengono visualizzati nella pagina aggregato/Dettagli salute.

.Fasi
. Eseguire una delle seguenti operazioni:
+
[cols="2*"]
|===
| Per visualizzare le informazioni sulla capacità per... | Eseguire questa operazione... 


 a| 
Cluster
 a| 
.. Nella vista capacità: Tutti i cluster, fare clic su un cluster.
.. Nella pagina Cluster / Health details (Dettagli cluster/integrità), fare clic sulla scheda *Configuration* (Configurazione).
+
Il display mostra i nomi dei Tier cloud a cui è connesso il cluster.





 a| 
Aggregati
 a| 
.. Nella vista capacità: Tutti gli aggregati, fare clic su un aggregato in cui il campo tipo indica "`SSD (FabricPool)`" o "`HDD (FabricPool)`".
.. Nella pagina aggregato/Dettagli salute, fare clic sulla scheda *capacità*.
+
Il display mostra la capacità totale utilizzata nel Tier cloud.

.. Fare clic sulla scheda *Disk Information* (informazioni disco).
+
Il display mostra il nome del livello cloud e la capacità utilizzata.

.. Fare clic sulla scheda *Configurazione*.
+
Il display mostra il nome del livello cloud e altre informazioni dettagliate sul livello cloud.





 a| 
Volumi
 a| 
.. Nella vista capacità: Tutti i volumi, fare clic su un volume in cui viene visualizzato il nome di un criterio nel campo "`Tiering Policy`".
.. Nella pagina Volume / Health details (Dettagli volume/salute), fare clic sulla scheda *Configuration* (Configurazione).
+
Sul display viene visualizzato il nome del criterio di tiering FabricPool assegnato al volume.



|===
. Nella pagina *analisi del carico di lavoro* è possibile selezionare "`Cloud Tier View`" nell'area *Capacity Trend* per visualizzare la capacità utilizzata nel Performance Tier locale e nel Cloud Tier nel mese precedente.


Per ulteriori informazioni sugli aggregati FabricPool, vedere https://docs.netapp.com/us-en/ontap/disks-aggregates/index.html["Panoramica su dischi e aggregati"].
