---
permalink: install-vapp/reference_vmware_software_and_installation_requirements.html 
sidebar: sidebar 
keywords: vmware, software, installation, requirements 
summary: Il sistema VMware vSphere su cui si installa Unified Manager richiede versioni specifiche del sistema operativo e del software di supporto. 
---
= Software VMware e requisiti di installazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il sistema VMware vSphere su cui si installa Unified Manager richiede versioni specifiche del sistema operativo e del software di supporto.



== Software del sistema operativo

Sono supportate le seguenti versioni di VMware ESXi:

* ESXi 7.0 e 8.0


[NOTE]
====
Unified Manager OVA su sistemi VMware vSphere esegue Debian OS 11 (bullseye) internamente. Per informazioni sulle versioni dell'hardware della macchina virtuale supportate dalle versioni supportate dei server ESXi, fare riferimento alla documentazione VMware.

====
Sono supportate le seguenti versioni di vSphere:

* VMware vCenter Server 7.0 e 8.0


Consulta la matrice di interoperabilità per l'elenco completo e aggiornato delle versioni di ESXi supportate.

http://mysupport.netapp.com/matrix["mysupport.netapp.com/matrix"]

L'ora del server VMware ESXi deve coincidere con quella del server NTP affinché l'appliance virtuale funzioni correttamente. La sincronizzazione dell'ora del server VMware ESXi con l'ora del server NTP impedisce un errore di tempo.



== Requisiti di installazione

VMware High Availability per l'appliance virtuale Unified Manager è supportata.

Se si implementa un datastore NFS su un sistema storage che esegue il software ONTAP, utilizzare il plug-in NFS NetApp per VMware VAAI per utilizzare il thick provisioning.

Se l'implementazione non riesce utilizzando l'ambiente abilitato per l'alta disponibilità a causa di risorse insufficienti, potrebbe essere necessario modificare le opzioni della macchina virtuale del cluster disattivando la priorità di riavvio della macchina virtuale e lasciando attiva la risposta di isolamento dell'host.


NOTE: Durante l'installazione o l'aggiornamento di Unified Manager, le patch di sicurezza e il software di terze parti richiesti vengono installati o aggiornati automaticamente su un sistema VMware vSphere. Poiché i processi di installazione e aggiornamento di Unified Manager controllano questi componenti, non tentare di eseguire un'installazione o un aggiornamento standalone di alcun componente di terze parti.
