---
permalink: install-vapp/task_upgrade_unified_manager_vapp.html 
sidebar: sidebar 
keywords: upgrade, unified manager 
summary: 'È possibile eseguire l"aggiornamento a Unified Manager su VMware vSphere' 
---
= Aggiornamento di Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile aggiornare Active IQ Unified Manager alla versione 9,16 solo dalla versione 9,13 o 9,14.

Durante il processo di aggiornamento, Unified Manager non è disponibile. Prima di eseguire l'aggiornamento di Unified Manager, è necessario completare tutte le operazioni in esecuzione.

Se Unified Manager è associato a un'istanza di OnCommand Workflow Automation e sono disponibili nuove versioni del software per entrambi i prodotti, è necessario scollegare i due prodotti e impostare una nuova connessione per l'automazione del flusso di lavoro dopo aver eseguito gli aggiornamenti. Se si esegue un aggiornamento a uno solo dei prodotti, dopo l'aggiornamento è necessario accedere a Workflow Automation e verificare che stia ancora acquisendo dati da Unified Manager.

.Fasi
. Seguire la procedura descritta in link:task_download_unified_manager_iso_image_vapp.html["Scarica l'immagine ISO di Unified Manager"].
. Inoltre, seguire la procedura descritta in link:task_upgrade_unified_manager_virtual_appliance_vapp.html["Aggiorna Unified Manager"].

