---
permalink: install-vapp/task_restart_unified_manager_virtual_machine.html 
sidebar: sidebar 
keywords: restart, unified manager, virtual, machine 
summary: 'È possibile riavviare la macchina virtuale (VM) di Unified Manager dalla console di manutenzione. Riavviare la macchina virtuale dopo aver generato un nuovo certificato di protezione o in caso di problemi con la macchina virtuale.' 
---
= Riavvio della macchina virtuale di Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile riavviare la macchina virtuale (VM) di Unified Manager dalla console di manutenzione. Riavviare la macchina virtuale dopo aver generato un nuovo certificato di protezione o in caso di problemi con la macchina virtuale.

*Cosa ti serve*

* L'appliance virtuale deve essere accesa.
* L'utente deve essere connesso alla console di manutenzione di Unified Manager come utente di manutenzione.


È inoltre possibile riavviare la macchina virtuale da vSphere utilizzando l'opzione VMware *Restart Guest*.

.Fasi
. Nella console di manutenzione, selezionare *Configurazione del sistema* > *riavvio della macchina virtuale*.
. Avviare l'interfaccia utente Web di Unified Manager dal browser ed effettuare l'accesso.


*Informazioni correlate*

https://www.vmware.com/support/developer/PowerCLI/PowerCLI41/html/Restart-VMGuest.html["Guida ai cmdlet di VMware vSphere PowerCLI: Restart-VMGuest"]
