---
permalink: install-vapp/task_upgrade_unified_manager_virtual_appliance_vapp.html 
sidebar: sidebar 
keywords: upgrade, unified manager, virtual, appliance 
summary: 'È possibile aggiornare l"appliance virtuale di Unified Manager' 
---
= Aggiornamento dell'appliance virtuale di Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile aggiornare l'appliance virtuale Active IQ Unified Manager dalle versioni 9,13 o 9,14 alla 9,16.

.Prima di iniziare
Verificare quanto segue:

* Il file di aggiornamento, l'immagine ISO, è stato scaricato dal NetApp Support Site.
* Il sistema su cui si esegue l'aggiornamento di Unified Manager soddisfa i requisiti di sistema e software.
+
Vedere link:concept_virtual_infrastructure_or_hardware_system_requirements.html["Requisiti dell'infrastruttura virtuale"].

+
Vedere link:reference_vmware_software_and_installation_requirements.html["Software VMware e requisiti di installazione"].

* Per gli utenti di vSphere 6.5 e versioni successive, è stata installata VMware Remote Console (VMRC).
* Durante l'aggiornamento, potrebbe essere richiesto di confermare se si desidera mantenere le impostazioni predefinite precedenti per la conservazione dei dati sulle prestazioni per 13 mesi o se si desidera modificarli in 6 mesi. Dopo la conferma, i dati storici delle performance vengono eliminati dopo 6 mesi.
* Si dispone delle seguenti informazioni:
+
** Credenziali di accesso per il NetApp Support Site
** Credenziali per l'accesso a VMware vCenter Server e vSphere Web Client
** Credenziali per l'utente di manutenzione di Unified Manager




Durante il processo di aggiornamento, Unified Manager non è disponibile. Prima di eseguire l'aggiornamento di Unified Manager, è necessario completare tutte le operazioni in esecuzione.

Se si dispone di Workflow Automation e Unified Manager associati, aggiornare manualmente il nome host in Workflow Automation.

.Fasi
. In vSphere Client, fare clic su *Home* > *Inventory* > *VM e modelli*.
. Selezionare la macchina virtuale (VM) su cui è installata l'appliance virtuale Unified Manager.
. Se la macchina virtuale di Unified Manager è in esecuzione, accedere a *Riepilogo* > *comandi* > *Chiudi sessione ospite*.
. Creare una copia di backup, ad esempio uno snapshot o un clone, della macchina virtuale di Unified Manager per creare un backup coerente con l'applicazione.
. Dal client vSphere, accendere Unified Manager VM.
. Avviare VMware Remote Console.
. Fare clic sull'icona *CDROM* e selezionare *Connect to Disk Image file (.iso)*.
. Selezionare `ActiveIQUnifiedManager-<version>-virtual-update.iso` E fare clic su *Apri*.
. Fare clic sulla scheda *Console*.
. Accedere alla console di manutenzione di Unified Manager.
. Nel menu principale, selezionare *Upgrade*.
+
Viene visualizzato un messaggio che indica che Unified Manager non è disponibile durante il processo di aggiornamento e che deve riprendere dopo il completamento.

. Tipo `y` per continuare.
+
Viene visualizzato un avviso che ricorda di eseguire il backup della macchina virtuale su cui risiede l'appliance virtuale.

. Tipo `y` per continuare.
+
Il processo di aggiornamento e il riavvio dei servizi di Unified Manager possono richiedere alcuni minuti.

. Premere un tasto qualsiasi per continuare.
+
L'utente viene disconnesso automaticamente dalla console di manutenzione.

. *Opzionale:* accedere alla console di manutenzione e verificare la versione di Unified Manager.


È possibile avviare l'interfaccia utente Web in una nuova finestra di un browser Web supportato ed effettuare l'accesso per utilizzare la versione aggiornata di Unified Manager. Tenere presente che è necessario attendere il completamento del processo di rilevamento prima di eseguire qualsiasi attività nell'interfaccia utente.
