---
permalink: install-vapp/task_restart_unified_manager_virtual_machine.html 
sidebar: sidebar 
keywords: restart, unified manager, virtual, machine 
summary: 'È possibile riavviare la macchina virtuale (VM) di Unified Manager dalla console di manutenzione. Riavviare la macchina virtuale dopo aver generato un nuovo certificato di protezione o in caso di problemi con la macchina virtuale.' 
---
= Riavviare la macchina virtuale di Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile riavviare la macchina virtuale (VM) di Unified Manager dalla console di manutenzione. Riavviare la macchina virtuale dopo aver generato un nuovo certificato di protezione o in caso di problemi con la macchina virtuale.

.Prima di iniziare
* L'appliance virtuale deve essere accesa.
* L'utente deve essere connesso alla console di manutenzione di Unified Manager come utente di manutenzione.


È anche possibile riavviare la macchina virtuale da vSphere utilizzando l'opzione VMware *Riavvia Guest*. Fare riferimento a  https://developer.broadcom.com/powercli/latest/vmware.vimautomation.core/commands/restart-vmguest/["il cmdlet Restart-VMGuest nel riferimento ai CMDLET VMware vSphere PowerCLI di Broadcom."^]

.Fasi
. Nella console di manutenzione, selezionare *Configurazione del sistema* > *riavvio della macchina virtuale*.
. Avviare l'interfaccia utente Web di Unified Manager dal browser ed effettuare l'accesso.

