---
permalink: install-windows/task_change_jboss_password_on_windows.html 
sidebar: sidebar 
keywords: change, jboss, password 
summary: 'È possibile reimpostare la password JBoss specifica dell"istanza impostata durante l"installazione. È possibile reimpostare la password facoltativamente, nel caso in cui il sito richieda questa funzionalità di sicurezza per ignorare l"impostazione di installazione di Unified Manager. Questa operazione modifica anche la password utilizzata da JBoss per accedere a MySQL.' 
---
= Modifica della password JBoss
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile reimpostare la password JBoss specifica dell'istanza impostata durante l'installazione. È possibile reimpostare la password facoltativamente, nel caso in cui il sito richieda questa funzionalità di sicurezza per ignorare l'impostazione di installazione di Unified Manager. Questa operazione modifica anche la password utilizzata da JBoss per accedere a MySQL.

*Cosa ti serve*

* È necessario disporre dei privilegi di amministratore di Windows per il sistema su cui è installato Unified Manager.
* Devi avere la password per l'utente root MySQL.
* Dovresti essere in grado di accedere al servizio fornito da NetApp `password.bat` script nella directory
+
`C:\Program Files\NetApp\essentials\bin`.



.Fasi
. Accedere come utente amministratore sul computer host di Unified Manager.
. Utilizzare la console dei servizi Windows per arrestare i seguenti servizi di Unified Manager:
+
** Servizio di acquisizione NetApp Active IQ (Ocie-au)
** Servizio server di gestione NetApp Active IQ (Oncommandsvc)


. Avviare `password.bat` script per avviare il processo di modifica della password:
+
`C:\Program Files\NetApp\essentials\bin> password.bat resetJBossPassword`

. Quando richiesto, inserire la password dell'utente root MySQL.
. Quando richiesto, inserire la nuova password utente JBoss, quindi immetterla di nuovo per confermarla.
+
Tenere presente che la password deve essere compresa tra 8 e 16 caratteri e deve contenere almeno una cifra, caratteri maiuscoli e minuscoli e almeno uno dei seguenti caratteri speciali:

+
`+!@%^*-_+=[]:<>.?/~+`

. Al termine dello script, avviare i servizi di Unified Manager utilizzando la console dei servizi Windows:
+
** Servizio server di gestione NetApp Active IQ (Oncommandsvc)
** Servizio di acquisizione NetApp Active IQ (Ocie-au)


. Una volta avviati tutti i servizi, è possibile accedere all'interfaccia utente di Unified Manager.

