---
permalink: install-windows/task_uninstall_third_party_products.html 
sidebar: sidebar 
keywords: MS Visual C++, python, uninstall, uninstalling, 9.18 
summary: Come disinstallare prodotti di terze parti, inclusi Python e Microsoft Visual C++. 
---
= Disinstalla i prodotti di terze parti in Active IQ Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo l'aggiornamento di Unified Manager, puoi disinstallare prodotti di terze parti, come Python o Microsoft Visual C++ 2013. Questa opzione è facoltativa.



[[uninstall-python]]
== Disinstallare Python

.Fasi
. Dal *pannello di controllo*, selezionare *programmi* > *programmi e funzionalità*.
. Selezionare Python dall'elenco dei programmi.
. Seleziona *Disinstalla questo programma*.  Disinstallare qualsiasi versione di Python tranne la 3.13.3.  Assicurati di mantenere la versione 3.13.3 di Python.




[[uninstall-microsoft-visual-c-2013]]
== Disinstallare Microsoft Visual C++ 2013

.Fasi
. Dal *pannello di controllo*, selezionare *programmi* > *programmi e funzionalità*.
. Selezionare *Microsoft Visual C++ 2013* dall'elenco dei programmi.
. Selezionare *Disinstalla questo programma*.

