---
permalink: install-windows/task_install_unified_manager_on_windows.html 
sidebar: sidebar 
keywords: install, unified manager 
summary: È possibile installare Unified Manager per monitorare e risolvere i problemi di capacità, disponibilità, performance e protezione dello storage dei dati. 
---
= Installazione di Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile installare Unified Manager per monitorare e risolvere i problemi di capacità, disponibilità, performance e protezione dello storage dei dati.

*Cosa ti serve*

* Il sistema su cui si intende installare Unified Manager deve soddisfare i requisiti di sistema e software.
+
Vedere link:concept_virtual_infrastructure_or_hardware_system_requirements.html["Requisiti di sistema hardware"].

+
Vedere link:reference_windows_software_and_installation_requirements.html["Software Windows e requisiti di installazione"].

+
[NOTE]
====
A partire da Unified Manager 9.5, OpenJDK viene fornito nel pacchetto di installazione e installato automaticamente. Oracle Java non è supportato a partire da Unified Manager 9.5.

====
* È necessario disporre dei privilegi di amministratore di Windows. Assicurarsi che il nome utente non inizi con un punto esclamativo "`!`". Installation of Unified Manager might fail if the user name of user running the installation begins with "`!`".
* Si dovrebbe disporre di un browser Web supportato.
* La password utente per la manutenzione di Unified Manager deve essere compresa tra 8 e 20 caratteri, deve contenere lettere maiuscole o minuscole, numeri e caratteri speciali.
* I seguenti caratteri speciali non sono consentiti nella stringa della password per l'utente di manutenzione o per l'utente root MySQL: " ' ` % , = & < > | ^ / ( ) [ ] ;:
+
Sono consentiti i seguenti caratteri speciali: ~ ! @ * - ? . + { }



.Fasi
. Accedere a Windows utilizzando l'account di amministratore locale predefinito.
. Accedere al NetApp Support Site e accedere alla pagina Download di Unified Manager:
+
https://mysupport.netapp.com/site/products/all/details/activeiq-unified-manager/downloads-tab["Sito di supporto NetApp"^]

. Selezionare la versione richiesta di Unified Manager e accettare il contratto di licenza con l'utente finale (EULA).
. Scaricare il file di installazione di Unified Manager Windows in una directory di destinazione sul sistema Windows.
. Accedere alla directory in cui si trova il file di installazione.
. Fare clic con il pulsante destro del mouse ed eseguire il file eseguibile del programma di installazione di Unified Manager (.exe) come amministratore.
+
Unified Manager rileva i pacchetti di terze parti mancanti o preinstallati e li elenca. Se i pacchetti di terze parti richiesti non sono installati nel sistema, Unified Manager li installa come parte dell'installazione.

. Fare clic su *Avanti*.
. Immettere il nome utente e la password per creare l'utente di manutenzione.
. Nella procedura guidata connessione database, inserire la password root MySQL.
. Fare clic su *Change* per specificare una nuova posizione per la directory di installazione di Unified Manager e la directory dei dati MySQL.
+
Se non si modifica la directory di installazione, Unified Manager viene installato nella directory di installazione predefinita.

. Fare clic su *Avanti*.
. Nella procedura guidata Ready to Install Shield, fare clic su *Install* (Installa).
. Al termine dell'installazione, fare clic su *fine*.
. Se sul sistema Windows è installato un software antivirus attivo, escludere manualmente i seguenti percorsi dalla scansione antivirus al termine dell'installazione:
+
** Directory dei dati di Unified Manager
** Directory di installazione di Unified Manager
** Directory dei dati MySQL




L'installazione crea più directory:

* Directory di installazione
+
Si tratta della directory principale di Unified Manager, specificata durante l'installazione. Esempio: `C:\Program Files\NetApp\`

* Directory dei dati MySQL
+
Questa è la directory in cui sono memorizzati i database MySQL, specificata durante l'installazione. Esempio: `C:\ProgramData\MySQL\MySQLServerData\`

* Directory Java
+
Questa è la directory in cui è installato OpenJDK. Esempio: `C:\Program Files\NetApp\JDK\`

* Directory dei dati dell'applicazione di Unified Manager (appDataDir)
+
Questa è la directory in cui vengono memorizzati tutti i dati generati dall'applicazione. Sono inclusi log, bundle di supporto, backup e tutti gli altri dati aggiuntivi. Esempio: `C:\ProgramData\NetApp\OnCommandAppData\`



È possibile accedere all'interfaccia utente Web per eseguire la configurazione iniziale di Unified Manager, come descritto in link:../config/concept_configure_unified_manager.html["Configurazione di Active IQ Unified Manager"].
