---
permalink: config/concept_maintenance_console_menu.html 
sidebar: sidebar 
keywords: maintenance, console, menus 
summary: La console di manutenzione è composta da diversi menu che consentono di gestire e gestire funzioni speciali e impostazioni di configurazione del server Unified Manager. 
---
= Menu della console di manutenzione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La console di manutenzione è composta da diversi menu che consentono di gestire e gestire funzioni speciali e impostazioni di configurazione del server Unified Manager.

A seconda del sistema operativo su cui è stato installato Unified Manager, la console di manutenzione è composta dai seguenti menu:

* Upgrade di Unified Manager (solo VMware)
* Configurazione di rete (solo VMware)
* Configurazione del sistema (solo VMware)
+
.. Supporto/Diagnostica
.. Reimposta certificato server
.. Provider di dati esterno
.. Backup Restore (Ripristino backup
.. Configurazione dell'intervallo di polling delle performance
.. Disattiva l'autenticazione SAML
.. Visualizzare/modificare le porte dell'applicazione
.. Configurazione del registro di debug
.. Controlla l'accesso alla porta MySQL 3306
.. Esci




Selezionare il numero dall'elenco per accedere all'opzione di menu specifica. Ad esempio, per il backup e il ripristino, selezionare _4_.
