---
permalink: config/concept_what_role_based_access_control_does.html 
sidebar: sidebar 
keywords: role-based, access, control 
summary: 'RBAC (role-based access control) consente agli amministratori di gestire gruppi di utenti definendo i ruoli. Se è necessario limitare l"accesso per funzionalità specifiche agli amministratori selezionati, è necessario impostare account amministratore per tali amministratori. Se si desidera limitare le informazioni che gli amministratori possono visualizzare e le operazioni che possono eseguire, è necessario applicare i ruoli agli account amministratore creati.' 
---
= Scopri il controllo degli accessi in base al ruolo in Active IQ Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
RBAC (in base al ruolo, role-based access control) offre la possibilità di controllare chi ha accesso a varie funzionalità e risorse nel server Active IQ Unified Manager. RBAC permette agli amministratori di gestire gruppi di utenti definendo i ruoli. Se hai bisogno di limitare l'accesso a specifiche funzionalità per determinati amministratori, devi creare account amministratore per loro. Se vuoi limitare le informazioni che gli amministratori possono visualizzare e le operazioni che possono eseguire, devi applicare ruoli agli account amministratore che crei.

Il server di gestione utilizza RBAC per le autorizzazioni di accesso utente e ruolo. Se non sono state modificate le impostazioni predefinite del server di gestione per l'accesso dell'utente amministrativo, non è necessario effettuare l'accesso per visualizzarle.

Quando si avvia un'operazione che richiede privilegi specifici, il server di gestione richiede di effettuare l'accesso. Ad esempio, per creare account amministratore, è necessario effettuare l'accesso con l'account amministratore dell'applicazione.
