---
permalink: config/task_configure_unified_manager_to_send_alert_notifications.html 
sidebar: sidebar 
keywords: configure, unified manager, send, alert, notifications 
summary: 'È possibile configurare Unified Manager in modo che invii notifiche che avvisano l"utente in merito a eventi nel proprio ambiente. Prima di poter inviare le notifiche, è necessario configurare diverse altre opzioni di Unified Manager.' 
---
= Configurazione di Unified Manager per l'invio di notifiche di avviso
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile configurare Unified Manager in modo che invii notifiche che avvisano l'utente in merito a eventi nel proprio ambiente. Prima di poter inviare le notifiche, è necessario configurare diverse altre opzioni di Unified Manager.

*Cosa ti serve*

È necessario disporre del ruolo di amministratore dell'applicazione.

Dopo aver implementato Unified Manager e aver completato la configurazione iniziale, è necessario configurare l'ambiente in modo da attivare avvisi e generare messaggi e-mail di notifica o trap SNMP in base alla ricezione degli eventi.

.Fasi
. link:task_configure_event_notification_settings.html["Configurare le impostazioni di notifica degli eventi"].
+
Se si desidera inviare notifiche di avviso quando si verificano determinati eventi nell'ambiente, è necessario configurare un server SMTP e fornire un indirizzo e-mail da cui inviare la notifica di avviso. Se si desidera utilizzare i trap SNMP, è possibile selezionare tale opzione e fornire le informazioni necessarie.

. link:task_enable_remote_authentication.html["Abilitare l'autenticazione remota"].
+
Se si desidera che gli utenti LDAP o Active Directory remoti accedano all'istanza di Unified Manager e ricevano notifiche di avviso, è necessario attivare l'autenticazione remota.

. link:task_add_authentication_servers.html["Aggiungere server di autenticazione"].
+
È possibile aggiungere server di autenticazione in modo che gli utenti remoti all'interno del server di autenticazione possano accedere a Unified Manager.

. link:task_add_users.html["Aggiungere utenti"].
+
È possibile aggiungere diversi tipi di utenti locali o remoti e assegnare ruoli specifici. Quando si crea un avviso, si assegna a un utente la ricezione delle notifiche.

. link:task_add_alerts.html["Aggiungere avvisi"].
+
Dopo aver aggiunto l'indirizzo e-mail per l'invio delle notifiche, aver aggiunto gli utenti per la ricezione delle notifiche, aver configurato le impostazioni di rete e configurato le opzioni SMTP e SNMP necessarie per l'ambiente, è possibile assegnare gli avvisi.


