---
permalink: config/task_configure_event_notification_settings.html 
sidebar: sidebar 
keywords: configure, event, notification, settings 
summary: 'È possibile configurare Unified Manager in modo che invii notifiche di avviso quando viene generato un evento o quando viene assegnato un evento a un utente. È possibile configurare il server SMTP utilizzato per inviare l"avviso e impostare vari meccanismi di notifica, ad esempio le notifiche di avviso possono essere inviate come e-mail o trap SNMP.' 
---
= Configurazione delle impostazioni di notifica degli eventi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile configurare Unified Manager in modo che invii notifiche di avviso quando viene generato un evento o quando viene assegnato un evento a un utente. È possibile configurare il server SMTP utilizzato per inviare l'avviso e impostare vari meccanismi di notifica, ad esempio le notifiche di avviso possono essere inviate come e-mail o trap SNMP.

.Prima di iniziare
È necessario disporre delle seguenti informazioni:

* Indirizzo e-mail da cui viene inviata la notifica di avviso
+
L'indirizzo e-mail viene visualizzato nel campo "`da`" nelle notifiche di avviso inviate. Se non è possibile recapitarlo per qualsiasi motivo, questo indirizzo e-mail viene utilizzato anche come destinatario per la posta non recapitabile.

* Nome host del server SMTP, nome utente e password per accedere al server
* Nome host o indirizzo IP dell'host di destinazione trap che riceverà il trap SNMP, oltre alla versione SNMP, alla porta trap in uscita, alla community e ad altri valori di configurazione SNMP richiesti
+
Per specificare più destinazioni di trap, separare ciascun host con una virgola. In questo caso, tutte le altre impostazioni SNMP, ad esempio versione e porta trap in uscita, devono essere le stesse per tutti gli host dell'elenco.



È necessario disporre del ruolo di amministratore dell'applicazione o di amministratore dello storage.

.Fasi
. Nel riquadro di navigazione a sinistra, fare clic su *Generale* > *Notifiche*.
. Nella pagina Notifiche, configurare le impostazioni appropriate.
+
*Note:*

+
** Se l'indirizzo da è pre-compilato con l'indirizzo "+ActiveIQUnifiedManager@localhost.com+", devi cambiarlo in un indirizzo e-mail reale e funzionante per assicurarti che tutte le notifiche e-mail siano inviate correttamente.
** Se il nome host del server SMTP non può essere risolto, è possibile specificare l'indirizzo IP (IPv4 o IPv6) del server SMTP invece del nome host.


. Fare clic su *Save* (Salva).
. Se è stata selezionata l'opzione *Use STARTTLS* or *Use SSL* (Usa STARTTLS* o *Use SSL*), dopo aver fatto clic sul pulsante *Save* (Salva) viene visualizzata una pagina del certificato. Verificare i dettagli del certificato e accettare il certificato per salvare le impostazioni di notifica.
+
Per visualizzare i dettagli del certificato, fare clic sul pulsante *View Certificate Details* (Visualizza dettagli certificato). Se il certificato esistente è scaduto, deselezionare la casella *Usa STARTTLS* o *Usa SSL*, salvare le impostazioni di notifica e selezionare nuovamente la casella *Usa STARTTLS* o *Usa SSL* per visualizzare un nuovo certificato.


