---
permalink: config/task_download_an_https_certificate_sign_request_ocf.html 
sidebar: sidebar 
keywords: download, https, certificate, signing, request 
summary: 'È possibile scaricare una richiesta di firma della certificazione per il certificato di protezione HTTPS corrente in modo da fornire il file a un"autorità di certificazione da firmare. Un certificato con firma CA aiuta a prevenire gli attacchi man-in-the-middle e offre una protezione migliore rispetto a un certificato autofirmato.' 
---
= Download di una richiesta di firma del certificato HTTPS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile scaricare una richiesta di firma della certificazione per il certificato di protezione HTTPS corrente in modo da fornire il file a un'autorità di certificazione da firmare. Un certificato con firma CA aiuta a prevenire gli attacchi man-in-the-middle e offre una protezione migliore rispetto a un certificato autofirmato.

*Cosa ti serve*

È necessario disporre del ruolo di amministratore dell'applicazione.

.Fasi
. Nel riquadro di spostamento a sinistra, fare clic su *Generale* > *certificato HTTPS*.
. Fare clic su *Scarica richiesta firma certificato HTTPS*.
. Salvare `<hostname>.csr` file.


È possibile fornire il file a un'autorità di certificazione per firmare e installare il certificato firmato.
