---
permalink: config/task_install_ca_signed_and_returned_https_certificate.html 
sidebar: sidebar 
keywords: install, ca signed, returned, https, certificate 
summary: 'È possibile caricare e installare un certificato di sicurezza dopo che un"autorità di certificazione ha firmato e restituito il certificato. Il file caricato e installato deve essere una versione firmata del certificato autofirmato esistente. Un certificato con firma CA aiuta a prevenire gli attacchi man-in-the-middle e offre una protezione migliore rispetto a un certificato autofirmato.' 
---
= Installa un certificato HTTPS firmato e restituito da una CA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile caricare e installare un certificato di sicurezza dopo che un'autorità di certificazione ha firmato e restituito il certificato. Il file caricato e installato deve essere una versione firmata del certificato autofirmato esistente. Un certificato con firma CA aiuta a prevenire gli attacchi man-in-the-middle e offre una protezione migliore rispetto a un certificato autofirmato.

*Cosa prima di iniziare

È necessario aver completato le seguenti operazioni:

* Il file Certificate Signing Request è stato scaricato e firmato da un'autorità di certificazione
* La catena di certificati è stata salvata in formato PEM
* Inclusi tutti i certificati nella catena, dal certificato del server Unified Manager al certificato di firma root, inclusi eventuali certificati intermedi presenti


È necessario disporre del ruolo di amministratore dell'applicazione.

[NOTE]
====
Se la validità del certificato per il quale è stata creata una CSR è superiore a 397 giorni, la validità verrà ridotta a 397 giorni dalla CA prima della firma e della restituzione del certificato

====
.Fasi
. Nel riquadro di spostamento a sinistra, fare clic su *Generale* > *certificato HTTPS*.
. Fare clic su *Installa certificato HTTPS*.
. Nella finestra di dialogo visualizzata, fare clic su *Scegli file...* per individuare il file da caricare.
. Selezionare il file, quindi fare clic su *Installa* per installarlo.
+
Per ulteriori informazioni, vedere link:concept_install_https_certificate_generated_using_external_tools.html["Installazione di un certificato HTTPS generato utilizzando strumenti esterni"].





== Esempio di catena di certificati

Nell'esempio seguente viene illustrato come potrebbe essere visualizzato il file di catena del certificato:

[listing]
----
-----BEGIN CERTIFICATE-----
<*Server certificate*>
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
<*Intermediate certificate \#1 (if present)*>
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
<*Intermediate certificate \#2 (if present)*>
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
<*Root signing certificate*>
-----END CERTIFICATE-----
----