---
permalink: config/task_test_configuration_of_authentication_servers_um_6_0.html 
sidebar: sidebar 
keywords: test, configuration, authentication servers 
summary: È possibile convalidare la configurazione dei server di autenticazione per garantire che il server di gestione sia in grado di comunicare con essi. È possibile convalidare la configurazione ricercando un utente remoto o un gruppo remoto dai server di autenticazione e autenticandoli utilizzando le impostazioni configurate. 
---
= Verifica della configurazione dei server di autenticazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile convalidare la configurazione dei server di autenticazione per garantire che il server di gestione sia in grado di comunicare con essi. È possibile convalidare la configurazione ricercando un utente remoto o un gruppo remoto dai server di autenticazione e autenticandoli utilizzando le impostazioni configurate.

*Cosa ti serve*

* È necessario aver attivato l'autenticazione remota e configurato il servizio di autenticazione in modo che il server Unified Manager possa autenticare l'utente remoto o il gruppo remoto.
* È necessario aggiungere i server di autenticazione in modo che il server di gestione possa cercare l'utente remoto o il gruppo remoto da questi server e autenticarli.
* È necessario disporre del ruolo di amministratore dell'applicazione.


Se il servizio di autenticazione è impostato su Active Directory e si sta convalidando l'autenticazione degli utenti remoti che appartengono al gruppo primario del server di autenticazione, le informazioni sul gruppo primario non vengono visualizzate nei risultati dell'autenticazione.

.Fasi
. Nel riquadro di spostamento di sinistra, fare clic su *Generale* > *autenticazione remota*.
. Fare clic su *Test Authentication*.
. Nella finestra di dialogo Test User, specificare il nome utente e la password dell'utente remoto o il nome utente del gruppo remoto, quindi fare clic su *Test*.
+
Se si sta autenticando un gruppo remoto, non è necessario immettere la password.


