---
permalink: config/task_change_local_user_password.html 
sidebar: sidebar 
keywords: change, local, user, password 
summary: È possibile modificare la password di accesso utente locale per evitare potenziali rischi per la sicurezza. 
---
= Modifica della password utente locale
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile modificare la password di accesso utente locale per evitare potenziali rischi per la sicurezza.

*Cosa ti serve*

Devi essere connesso come utente locale.

Le password per l'utente di manutenzione e per gli utenti remoti non possono essere modificate seguendo questa procedura. Per modificare la password di un utente remoto, contattare l'amministratore della password. Per modificare la password utente per la manutenzione, vedere link:task_use_maintenance_console.html["Utilizzando la console di manutenzione"].

.Fasi
. Accedere a Unified Manager.
. Dalla barra dei menu superiore, fare clic sull'icona dell'utente, quindi fare clic su *Change Password* (Modifica password).
+
L'opzione *Change Password* (Modifica password) non viene visualizzata se si è utenti remoti.

. Nella finestra di dialogo Change Password (Modifica password), immettere la password corrente e la nuova password.
. Fare clic su *Save* (Salva).


Se Unified Manager è configurato in una configurazione ad alta disponibilità, è necessario modificare la password sul secondo nodo dell'installazione. Entrambe le istanze devono avere la stessa password.
