---
permalink: config/task_change_umadmin_password_on_rhel.html 
sidebar: sidebar 
keywords: change, umadmin, password, linux systems 
summary: 'Per motivi di sicurezza, è necessario modificare la password predefinita per l"utente di Unified Manager umadmin subito dopo aver completato il processo di installazione. Se necessario, è possibile modificare nuovamente la password in un secondo momento.' 
---
= Modifica della password di umadmin sui sistemi Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per motivi di sicurezza, è necessario modificare la password predefinita per l'utente di Unified Manager umadmin subito dopo aver completato il processo di installazione. Se necessario, è possibile modificare nuovamente la password in un secondo momento.

*Cosa ti serve*

* Unified Manager deve essere installato su un sistema Red Hat Enterprise Linux o CentOS Linux.
* È necessario disporre delle credenziali utente root per il sistema Linux su cui è installato Unified Manager.


.Fasi
. Accedere come utente root al sistema Linux su cui è in esecuzione Unified Manager.
. Modificare la password di umadmin:
+
`passwd umadmin`

+
Il sistema richiede di inserire una nuova password per l'utente umadmin.


