---
permalink: install-linux/reference_users_created_in_unified_manager.html 
sidebar: sidebar 
keywords: users, created, unified manager, installation 
summary: 'Quando si installa Unified Manager su Red Hat Enterprise Linux, i seguenti utenti vengono creati da Unified Manager e da utility di terze parti: Umadmin, jboss e mysql.' 
---
= Utenti creati durante l'installazione di Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si installa Unified Manager su Red Hat Enterprise Linux, i seguenti utenti vengono creati da Unified Manager e da utility di terze parti: Umadmin, jboss e mysql.

* *umadmin*
+
Utilizzato per accedere a Unified Manager per la prima volta. A questo utente viene assegnato un ruolo utente "`Application Administrator`" ed è configurato come tipo "`Maintenance User`". Questo utente viene creato da Unified Manager.

* *jboss*
+
Utilizzato per eseguire i servizi di Unified Manager correlati all'utility JBoss. Questo utente viene creato da Unified Manager.

* *mysql*
+
Utilizzato per eseguire query di database MySQL di Unified Manager. Questo utente viene creato dall'utility MySQL di terze parti.



Oltre a questi utenti, Unified Manager crea anche gruppi corrispondenti: Maintenance, jboss e mysql. I gruppi Maintenance e jboss vengono creati da Unified Manager, mentre il gruppo mysql viene creato da un'utility di terze parti.

[NOTE]
====
Se è stata creata una home directory personalizzata e definita la propria password utente umadmin prima di installare Unified Manager, il programma di installazione non ricreerà il gruppo di manutenzione o l'utente umadmin.

====