---
permalink: install-linux/task_manually_configure_epel_repository.html 
sidebar: sidebar 
keywords: manually, configure, epel repository 
summary: 'Se il sistema su cui si installa Unified Manager non ha accesso al repository Extra Packages for Enterprise Linux (EPEL), è necessario scaricare e configurare manualmente il repository per una corretta installazione.' 
---
= Configurazione manuale del repository EPEL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se il sistema su cui si installa Unified Manager non ha accesso al repository Extra Packages for Enterprise Linux (EPEL), è necessario scaricare e configurare manualmente il repository per una corretta installazione.

Il repository EPEL fornisce l'accesso alle utility di terze parti necessarie che devono essere installate nel sistema. Utilizzate il repository EPEL per installare Unified Manager su un sistema Red Hat Enterprise Linux.

.Fasi
. Scarica il repository EPEL per la tua installazione. Per la versione 8, scaricarla da:
+
`+wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm+`

+
Per la versione 9, scaricarla da:

+
`wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm`

. Configurare il repository EPEL:
+
`yum install epel-release-latest-<version>.noarch.rpm`



Per i sistemi Red Hat Enterprise Linux 8, se si dispone di repository interni con pacchetti RPM modulari, ad esempio `_javapackages-filesystem-<version>.module.rpm_`, assicurarsi che i metadati per i pacchetti modulari siano disponibili anche nello stesso repository.
