---
permalink: install-linux/task_change_jboss_password.html 
sidebar: sidebar 
keywords: change, jboss password 
summary: 'È possibile reimpostare la password JBoss specifica dell"istanza impostata durante l"installazione. È possibile reimpostare la password facoltativamente, nel caso in cui il sito richieda questa funzionalità di sicurezza per ignorare l"impostazione di installazione di Unified Manager. Questa operazione modifica anche la password utilizzata da JBoss per accedere a MySQL.' 
---
= Modifica della password JBoss
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile reimpostare la password JBoss specifica dell'istanza impostata durante l'installazione. È possibile reimpostare la password facoltativamente, nel caso in cui il sito richieda questa funzionalità di sicurezza per ignorare l'impostazione di installazione di Unified Manager. Questa operazione modifica anche la password utilizzata da JBoss per accedere a MySQL.

* È necessario disporre dell'accesso utente root al sistema Red Hat Enterprise Linux o CentOS su cui è installato Unified Manager.
* Devi essere in grado di accedere al servizio fornito da NetApp `password.sh` script nella directory `/opt/netapp/essentials/bin`.


.Fasi
. Accedere come utente root sul sistema.
. Arrestare i servizi di Unified Manager immettendo i seguenti comandi nell'ordine indicato:
+
`systemctl stop ocieau`

+
`systemctl stop ocie`

+
Non interrompere il software MySQL associato.

. Immettere il seguente comando per avviare il processo di modifica della password:
+
`/opt/netapp/essentials/bin/password.sh resetJBossPassword`

. Quando richiesto, inserire la nuova password JBoss, quindi immetterla una seconda volta per confermarla.
+
Tenere presente che la password deve essere compresa tra 8 e 16 caratteri e deve contenere almeno una cifra, caratteri maiuscoli e minuscoli e almeno uno dei seguenti caratteri speciali:

+
`+!@%^*-_+=[]:<>.?/~+`

. Al termine dello script, avviare i servizi di Unified Manager immettendo i seguenti comandi nell'ordine indicato:
+
`systemctl start ocie`

+
`systemctl start ocieau`

. Una volta avviati tutti i servizi, è possibile accedere all'interfaccia utente di Unified Manager.

