---
permalink: include/upgrade-path.html 
sidebar: sidebar 
keywords: supported upgrade path, upgrade path, n-2, which versions can be upgraded 
summary: Percorso di upgrade supportato 
---
= Percorso di aggiornamento supportato per le versioni di Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager supporta un percorso di aggiornamento specifico per ciascuna versione.

Non tutte le versioni di Unified Manager possono eseguire un aggiornamento in-place alle versioni successive. Gli aggiornamenti di Unified Manager sono limitati a un modello N-2, il che significa che un aggiornamento può essere eseguito solo nelle 2 release successive su tutte le piattaforme. Ad esempio, puoi eseguire un upgrade a Unified Manager 9,16 solo da Unified Manager 9,13 e 9,14.

Se si utilizza una versione precedente a quella supportata, l'istanza di Unified Manager deve essere prima aggiornata a una delle versioni supportate, quindi aggiornata alla versione corrente.

Ad esempio, se la versione installata è Unified Manager 9,9 e si desidera eseguire l'aggiornamento a Unified Manager 9,14, si seguono una sequenza di aggiornamenti.

.Esempio di percorso di aggiornamento:
. Aggiornamento 9,11 -> 9,13
. Aggiornamento 9,13 -> 9,14
. Aggiornamento 9,14 -> 9,16


Per ulteriori informazioni sulla matrice dei percorsi di aggiornamento, vedere questa sezione https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/Active_IQ_Unified_Manager/What_is_the_upgrade_path_for_Active_IQ_Unified_Manager_versions["Articolo della Knowledge base (KB)"].
