---
permalink: events/concept_manage_scripts.html 
sidebar: sidebar 
keywords: manage, scripts 
summary: 'È possibile utilizzare gli script per modificare o aggiornare automaticamente più oggetti di storage in Unified Manager. Lo script è associato a un avviso. Quando un evento attiva un avviso, lo script viene eseguito. È possibile caricare script personalizzati e testarne l"esecuzione quando viene generato un avviso.' 
---
= Gestione degli script
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare gli script per modificare o aggiornare automaticamente più oggetti di storage in Unified Manager. Lo script è associato a un avviso. Quando un evento attiva un avviso, lo script viene eseguito. È possibile caricare script personalizzati e testarne l'esecuzione quando viene generato un avviso.

Per impostazione predefinita, è attivata la possibilità di caricare gli script in Unified Manager ed eseguirli. Se l'organizzazione non desidera consentire questa funzionalità per motivi di sicurezza, è possibile disattivarla da *Storage Management* > *Feature Settings*.

*Informazioni correlate*

link:../config/task_enable_and_disable_ability_to_upload_scripts.html["Abilitazione e disabilitazione della capacità di caricare gli script"]
