---
permalink: events/reference_event_details_page.html 
sidebar: sidebar 
keywords: event, details, page 
summary: 'Dalla pagina Dettagli evento è possibile visualizzare i dettagli di un evento selezionato, ad esempio la gravità dell"evento, il livello di impatto, l"area di impatto e l"origine dell"evento. È inoltre possibile visualizzare ulteriori informazioni sulle possibili soluzioni per risolvere il problema.' 
---
= Pagina dei dettagli dell'evento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dalla pagina Dettagli evento è possibile visualizzare i dettagli di un evento selezionato, ad esempio la gravità dell'evento, il livello di impatto, l'area di impatto e l'origine dell'evento. È inoltre possibile visualizzare ulteriori informazioni sulle possibili soluzioni per risolvere il problema.

* *Nome evento*
+
Il nome dell'evento e l'ora dell'ultima visualizzazione dell'evento.

+
Per gli eventi che non riguardano le performance, mentre l'evento si trova nello stato New (nuovo) o Acknowledged (confermato), le ultime informazioni visualizzate non sono note e pertanto nascoste.

* *Descrizione dell'evento*
+
Una breve descrizione dell'evento.

+
In alcuni casi, nella descrizione dell'evento viene indicato un motivo per l'attivazione dell'evento.

* *Componente in conflitto*
+
Per gli eventi di performance dinamiche, questa sezione visualizza le icone che rappresentano i componenti logici e fisici del cluster. Se un componente è in conflitto, la relativa icona viene cerchiata ed evidenziata in rosso.

+
Per una descrizione dei componenti visualizzati, consulta la sezione _componenti del cluster e perché possono essere in conflitto_.



Le sezioni informazioni evento, Diagnosi del sistema e azioni consigliate sono descritte in altri argomenti.



== Pulsanti di comando

I pulsanti di comando consentono di eseguire le seguenti operazioni:

* Icona *Note*
+
Consente di aggiungere o aggiornare una nota sull'evento e di rivedere tutte le note lasciate da altri utenti.



*Menu azioni*

* *Assegna a me*
+
Assegna l'evento all'utente.

* *Assegna ad altri*
+
Apre la finestra di dialogo Assegna proprietario, che consente di assegnare o riassegnare l'evento ad altri utenti.

+
Quando si assegna un evento a un utente, il nome dell'utente e l'ora in cui l'evento è stato assegnato vengono aggiunti all'elenco degli eventi selezionati.

+
È inoltre possibile annullare l'assegnazione degli eventi lasciando vuoto il campo Ownership (proprietà).

* *Riconoscere*
+
Riconosce gli eventi selezionati in modo da non continuare a ricevere notifiche di avviso ripetute.

+
Quando si riconosce un evento, il nome utente e l'ora in cui si è confermato l'evento vengono aggiunti all'elenco degli eventi (riconosciuti da) per gli eventi selezionati. Quando si riconosce un evento, si assume la responsabilità della gestione di tale evento.

* *Contrassegna come risolto*
+
Consente di modificare lo stato dell'evento in Resolved (risolto).

+
Quando si risolve un evento, il nome utente e l'ora in cui l'evento è stato risolto vengono aggiunti all'elenco degli eventi (risolti da) per gli eventi selezionati. Dopo aver eseguito un'azione correttiva per l'evento, è necessario contrassegnare l'evento come risolto.

* *Aggiungi avviso*
+
Visualizza la finestra di dialogo Aggiungi avviso, che consente di aggiungere un avviso per l'evento selezionato.


