---
permalink: events/task_manage_host_system_resource_events.html 
sidebar: sidebar 
keywords: manage, host, system, resource, events 
summary: 'Unified Manager include un servizio che monitora i problemi relativi alle risorse sul sistema host su cui è installato Unified Manager. Problemi come la mancanza di spazio su disco disponibile o la mancanza di memoria nel sistema host possono attivare eventi della stazione di gestione visualizzati come messaggi banner nella parte superiore dell"interfaccia utente.' 
---
= Gestione degli eventi delle risorse del sistema host
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager include un servizio che monitora i problemi relativi alle risorse sul sistema host su cui è installato Unified Manager. Problemi come la mancanza di spazio su disco disponibile o la mancanza di memoria nel sistema host possono attivare eventi della stazione di gestione visualizzati come messaggi banner nella parte superiore dell'interfaccia utente.

Gli eventi delle stazioni di gestione indicano un problema con il sistema host su cui è installato Unified Manager. Alcuni esempi di problemi relativi alle stazioni di gestione includono lo spazio su disco insufficiente nel sistema host, Unified Manager non dispone di un normale ciclo di raccolta dei dati e il mancato completamento o il completamento ritardato dell'analisi delle statistiche a causa dell'avvio del successivo polling della raccolta.

A differenza di tutti gli altri messaggi di evento di Unified Manager, questi particolari avvisi e eventi critici della stazione di gestione vengono visualizzati in messaggi banner.

.Fase
. Per visualizzare le informazioni sugli eventi della stazione di gestione, eseguire le seguenti operazioni:
+
|===
| Se si desidera... | Eseguire questa operazione... 


 a| 
Visualizza i dettagli dell'evento
 a| 
Fare clic sul banner dell'evento per visualizzare la pagina Dettagli evento che contiene le soluzioni suggerite per il problema.



 a| 
Visualizzare tutti gli eventi delle stazioni di gestione
 a| 
.. Nel riquadro di spostamento di sinistra, fare clic su *Gestione eventi*.
.. Nel riquadro filtri della pagina inventario gestione eventi, fare clic sulla casella Stazione di gestione nell'elenco tipo di origine.


|===

