---
permalink: events/task_view_events_that_occurred_during_maintenance_window.html 
sidebar: sidebar 
keywords: view, events, occurred, maintenance, window 
summary: 'Se necessario, è possibile visualizzare gli eventi generati per tutti gli oggetti di storage durante una finestra di manutenzione di Unified Manager. La maggior parte degli eventi viene visualizzata nello stato obsoleto una volta completata la finestra di manutenzione e dopo aver eseguito il backup e l"esecuzione di tutte le risorse di sistema.' 
---
= Visualizzazione degli eventi verificatisi durante una finestra di manutenzione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se necessario, è possibile visualizzare gli eventi generati per tutti gli oggetti di storage durante una finestra di manutenzione di Unified Manager. La maggior parte degli eventi viene visualizzata nello stato obsoleto una volta completata la finestra di manutenzione e dopo aver eseguito il backup e l'esecuzione di tutte le risorse di sistema.

*Cosa ti serve*

Almeno una finestra di manutenzione deve essere completata prima che siano disponibili eventi.

Per impostazione predefinita, gli eventi che si sono verificati durante una finestra di manutenzione non vengono visualizzati nella pagina dell'inventario di gestione degli eventi.

.Fasi
. Nel riquadro di navigazione a sinistra, fare clic su *Eventi*.
+
Per impostazione predefinita, tutti gli eventi attivi (nuovi e riconosciuti) vengono visualizzati nella pagina inventario gestione eventi.

. Dal riquadro di visualizzazione, selezionare l'opzione *tutti gli eventi generati durante la manutenzione*.
+
Viene visualizzato l'elenco degli eventi che sono stati provati durante gli ultimi 7 giorni da tutte le sessioni della finestra di manutenzione e da tutti i cluster.

. Se sono state visualizzate più finestre di manutenzione per un singolo cluster, fare clic sull'icona del calendario *ora di attivazione* e selezionare il periodo di tempo per gli eventi della finestra di manutenzione che si desidera visualizzare.

