---
permalink: data-protection/task_view_protection_relationships_from_storage_vms_page.html 
sidebar: sidebar 
keywords: storage vm, viewing protection relationships 
summary: La pagina Storage VM consente di visualizzare lo stato delle relazioni di disaster recovery delle macchine virtuali di storage esistenti. 
---
= Visualizzazione delle relazioni di protezione dalla pagina Storage VM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilizzando la pagina Storage VM, è possibile visualizzare lo stato delle relazioni di disaster recovery delle macchine virtuali di storage esistenti`.

*Cosa ti serve*

È necessario disporre del ruolo di amministratore dell'applicazione o di amministratore dello storage.

Puoi anche esaminare i dettagli delle relazioni di protezione, tra cui lo stato di trasferimento e ritardo, l'origine e i dettagli di destinazione. È possibile pianificare i report o scaricare quelli esistenti nel formato richiesto. Il pulsante *Mostra/Nascondi* consente di aggiungere le colonne richieste ai report, in quanto non vengono visualizzate per impostazione predefinita.

.Fasi
. Nel riquadro di navigazione a sinistra, fare clic su *STORAGE* > *Storage VM*.
. Dal menu *VIEW*, selezionare *relazione* > *tutte le relazioni*.
+
La vista relazione: Tutte le relazioni viene visualizzata con tutte le VM di storage configurate.


