---
permalink: data-protection/task_abort_an_active_data_protection_transfer.html 
sidebar: sidebar 
keywords: abort, active data protection, transfer, volume relationships page, SnapMirror active sync 
summary: 'È possibile interrompere un trasferimento di protezione dei dati attivo quando si desidera interrompere una replica SnapMirror in corso. È inoltre possibile cancellare il checkpoint di riavvio per i trasferimenti successivi al trasferimento di riferimento. È possibile interrompere un trasferimento in caso di conflitto con un"altra operazione, ad esempio uno spostamento del volume.' 
---
= Interruzione di un trasferimento di protezione dei dati attivo dalla pagina Relazioni volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile interrompere un trasferimento di protezione dei dati attivo quando si desidera interrompere una replica SnapMirror in corso. È inoltre possibile cancellare il checkpoint di riavvio per i trasferimenti successivi al trasferimento di riferimento. È possibile interrompere un trasferimento in caso di conflitto con un'altra operazione, ad esempio uno spostamento del volume.


NOTE: Non è possibile interrompere le relazioni dei volumi protette dal gruppo di coerenza.

*Cosa ti serve*

* È necessario disporre del ruolo di amministratore dell'applicazione o di amministratore dello storage.
* È necessario aver impostato l'automazione del flusso di lavoro.


L'azione di interruzione non viene visualizzata nei seguenti casi:

* Se le impostazioni RBAC non consentono questa azione: Ad esempio, se si dispone solo di privilegi operatore
* Quando l'ID del volume è sconosciuto: Ad esempio, quando si dispone di una relazione tra cluster e il cluster di destinazione non è stato ancora rilevato


Non è possibile cancellare il checkpoint di riavvio per un trasferimento di riferimento.

.Fasi
. Per interrompere i trasferimenti per una o più relazioni di protezione, dalla pagina *Relazioni volume*, selezionare uno o più volumi e, sulla barra degli strumenti, fare clic su *Interrompi*.
+
Viene visualizzata la finestra di dialogo Interrompi trasferimento.

. Se si desidera cancellare il checkpoint di riavvio per un trasferimento che non è un trasferimento di riferimento, selezionare *Clear Checkpoint*.
. Fare clic su *continua*.
+
La finestra di dialogo Interrompi trasferimento viene chiusa e lo stato del processo di interruzione viene visualizzato nella parte superiore della pagina Relazioni volume, insieme a un collegamento ai dettagli del processo.

. *Opzionale:* fare clic sul collegamento *Visualizza dettagli* per accedere alla pagina *Dettagli lavoro* per ulteriori dettagli e per visualizzare l'avanzamento del lavoro.

