---
permalink: data-protection/task_create_snapvault_protection_relationship_from_health_volume_details.html 
sidebar: sidebar 
keywords: create, snapvault, protection, relationship, volume, health details page 
summary: È possibile creare una relazione SnapVault utilizzando la pagina dei dettagli relativi a volume/stato di salute in modo che i backup dei dati siano abilitati per scopi di protezione sui volumi. 
---
= Creazione di una relazione di protezione SnapVault dalla pagina dei dettagli relativi a volume/salute
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile creare una relazione SnapVault utilizzando la pagina dei dettagli relativi a volume/stato di salute in modo che i backup dei dati siano abilitati per scopi di protezione sui volumi.

*Cosa ti serve*

* È necessario disporre del ruolo di amministratore dell'applicazione o di amministratore dello storage.
* Per eseguire questa attività, è necessario aver impostato l'automazione del flusso di lavoro.


Il menu *Protect* non viene visualizzato nelle seguenti istanze:

* Se le impostazioni RBAC non consentono questa azione: Ad esempio, se si dispone solo di privilegi operatore
* Quando l'ID del volume è sconosciuto: Ad esempio, quando si dispone di una relazione tra cluster e il cluster di destinazione non è stato ancora rilevato


.Fasi
. Nella scheda *Protection* della pagina dei dettagli *Volume / Health*, fare clic con il pulsante destro del mouse su un volume nella vista della topologia che si desidera proteggere.
. Selezionare *Protect* > *SnapVault* dal menu.
+
Viene visualizzata la finestra di dialogo Configura protezione.

. Fare clic su *SnapVault* per visualizzare la scheda *SnapVault* e configurare le informazioni sulle risorse secondarie.
. Fare clic su *Advanced* (Avanzate) per impostare deduplica, compressione, crescita automatica e garanzia di spazio secondo necessità, quindi fare clic su *Apply* (Applica).
. Completare l'area *Destination Information* (informazioni destinazione) e l'area *Relationship Settings* (Impostazioni relazione) nella finestra di dialogo *Configure Protection* (Configura protezione).
. Fare clic su *Apply* (Applica).
+
Viene visualizzata nuovamente la pagina dei dettagli relativi a volume/salute.

. Fare clic sul collegamento al processo di configurazione della protezione nella parte superiore della pagina dei dettagli *Volume / Health*.
+
Viene visualizzata la pagina Dettagli lavoro.

. Fare clic su *Refresh* (Aggiorna) per aggiornare l'elenco delle attività e i dettagli delle attività associati al processo di configurazione della protezione e per determinare quando il processo è completo.
+
Una volta completate le attività di lavoro, le nuove relazioni vengono visualizzate nella vista topologia della pagina dei dettagli volume/salute.


