---
permalink: data-protection/task_resolve_protection_job_failure.html 
sidebar: sidebar 
keywords: resolve, protection, job failure 
summary: Questo flusso di lavoro fornisce un esempio di come è possibile identificare e risolvere un errore di un processo di protezione dalla dashboard di Unified Manager. 
---
= Risoluzione di un errore di un lavoro di protezione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Questo flusso di lavoro fornisce un esempio di come è possibile identificare e risolvere un errore di un processo di protezione dalla dashboard di Unified Manager.

*Cosa ti serve*

Poiché alcune attività di questo flusso di lavoro richiedono l'accesso mediante il ruolo di amministratore, è necessario conoscere i ruoli richiesti per utilizzare le varie funzionalità.

In questo scenario, puoi accedere alla pagina Dashboard per verificare se ci sono problemi con i tuoi processi di protezione. Nell'area incidente di protezione, si noterà la presenza di un incidente con interruzione del processo, che mostra un errore di errore relativo al processo di protezione non riuscito su un volume. Esaminare questo errore per determinare la possibile causa e la potenziale risoluzione.

.Fasi
. Nel pannello incidenti di protezione dell'area incidenti e rischi non risolti della dashboard, fare clic sull'evento *errore del processo di protezione*.
+
[TIP]
====
Il testo associato all'evento viene scritto nel modulo `object_name:/object_name - Error Name`, ad esempio `cluster2_src_svm:/cluster2_src_vol2 - Protection Job Failed`.

====
+
Viene visualizzata la pagina Dettagli evento relativa al processo di protezione non riuscito.

. Esaminare il messaggio di errore nel campo cause dell'area *Summary* per determinare il problema e valutare le potenziali azioni correttive.
+
Vedere link:task_identify_problem_for_failed_protection_job.html["Identificazione del problema ed esecuzione di azioni correttive per un lavoro di protezione non riuscito"].


