---
permalink: data-protection/task_monitor_jobs.html 
sidebar: sidebar 
keywords: monitor, jobs 
summary: 'È possibile utilizzare la pagina lavori per monitorare lo stato del lavoro e visualizzare le proprietà del lavoro, ad esempio il tipo di servizio di storage, lo stato, l"ora di inoltro e il tempo di completamento, per determinare se un lavoro è stato completato correttamente.' 
---
= Monitoraggio dei lavori
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare la pagina lavori per monitorare lo stato del lavoro e visualizzare le proprietà del lavoro, ad esempio il tipo di servizio di storage, lo stato, l'ora di inoltro e il tempo di completamento, per determinare se un lavoro è stato completato correttamente.

*Cosa ti serve*

È necessario disporre del ruolo di amministratore dell'applicazione o di amministratore dello storage.

.Fasi
. Nel riquadro di spostamento di sinistra, fare clic su *protezione* > *lavori*.
+
Viene visualizzata la pagina lavori.

. Visualizzare la colonna *Stato* per determinare lo stato dei job attualmente in esecuzione.
. Fare clic sul nome di un lavoro per visualizzare i dettagli relativi a tale lavoro.
+
Viene visualizzata la pagina Dettagli lavoro.


