---
permalink: data-protection/task_view_volume_protection_relationships.html 
sidebar: sidebar 
keywords: view, volume, protection relationships 
summary: 'Dalla vista relazione: Tutte le relazioni e dalla pagina Relazioni volume, è possibile visualizzare lo stato delle relazioni SnapMirror e SnapVault del volume esistente. È inoltre possibile esaminare i dettagli relativi alle relazioni di protezione, tra cui lo stato di trasferimento e ritardo, i dettagli di origine e destinazione, le informazioni di pianificazione e policy e così via.' 
---
= Visualizzazione delle relazioni di protezione dei volumi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dalla vista relazione: Tutte le relazioni e dalla pagina Relazioni volume, è possibile visualizzare lo stato delle relazioni SnapMirror e SnapVault del volume esistente. È inoltre possibile esaminare i dettagli relativi alle relazioni di protezione, tra cui lo stato di trasferimento e ritardo, i dettagli di origine e destinazione, le informazioni di pianificazione e policy e così via.

*Cosa ti serve*

È necessario disporre del ruolo di amministratore dell'applicazione o di amministratore dello storage.

Da questa pagina è inoltre possibile avviare i comandi di relazione.

.Fasi
. Nel riquadro di navigazione a sinistra, fare clic su *Storage* > *Volumes*.
. Dal menu Visualizza, selezionare *relazione* > *tutte le relazioni*.
+
Viene visualizzata la vista relazione: Tutte le relazioni.

. Scegliere uno dei seguenti metodi per visualizzare i dettagli della protezione del volume:
+
** Per visualizzare le informazioni correnti su tutte le relazioni del volume, rimanere nella pagina predefinita *tutte le relazioni*.
** Per visualizzare informazioni dettagliate sui trend di trasferimento dei volumi in un determinato periodo di tempo, nel menu View (Visualizza), selezionare Relationship (relazione): Last 1 Month Transfer Status (Stato trasferimento ultimo 1 mese) view (visualizzazione).
** Per visualizzare informazioni dettagliate sull'attività di trasferimento del volume giorno per giorno, nel menu View (Visualizza), selezionare Relationship: Last 1 Month Transfer Rate view (relazione: Vista tasso di trasferimento ultimo 1 mese).


+
[NOTE]
====
Le viste di trasferimento dei volumi visualizzano le informazioni solo per i volumi nelle relazioni asincrone, i volumi nelle relazioni sincrone non vengono visualizzati.

====

