---
permalink: data-protection/task_restore_data_use_health_volume_details_page.html 
sidebar: sidebar 
keywords: restore, data, volume, health details page 
summary: È possibile ripristinare file, directory o un intero volume sovrascritti o cancellati da una copia Snapshot utilizzando la funzione di ripristino nella pagina Dettagli volume / integrità. 
---
= Ripristino dei dati mediante le pagine dei dettagli volume e volume/salute
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile ripristinare file, directory o un intero volume sovrascritti o cancellati da una copia Snapshot utilizzando la funzione di ripristino nelle pagine dei dettagli volume e volume/integrità.

*Cosa ti serve*

È necessario disporre del ruolo di amministratore dell'applicazione o di amministratore dello storage.


NOTE: Prendere nota dei seguenti punti:

* Non è possibile ripristinare i flussi di file NTFS.
* L'opzione di ripristino non è disponibile quando:
+
** L'ID del volume è sconosciuto: Ad esempio, quando si dispone di una relazione tra cluster e il cluster di destinazione non è stato ancora rilevato.
** Il volume viene configurato per la replica sincrona di SnapMirror.




.Fasi
. Dal riquadro di navigazione a sinistra, selezionare *Storage > Volumes* (archiviazione > volumi).
. Selezionare il volume e fare clic sul pulsante *Restore* (Ripristina). In alternativa, fare clic sul volume per accedere a *Volume / Health details > Actions > Restore* (Dettagli volume/salute > azioni > Ripristino). Viene visualizzata la finestra di dialogo Restore (Ripristino). Per informazioni su questa pagina, vedere link:../data-protection/reference_restore_dialog_box.html["Finestra di dialogo Restore (Ripristina)"].
. Selezionare il volume e la copia Snapshot da cui si desidera ripristinare i dati, se diversi da quelli predefiniti.
. Selezionare gli elementi da ripristinare, ad esempio il LUN di origine.
+
È possibile ripristinare l'intero volume oppure specificare le cartelle e i file da ripristinare.

. Selezionare la posizione in cui si desidera ripristinare gli elementi selezionati: *Posizione originale* o *posizione esistente alternativa*.
. Se si seleziona una posizione esistente alternativa, effettuare una delle seguenti operazioni:
+
** Nel campo di testo Restore Path (percorso di ripristino), digitare il percorso in cui si desidera ripristinare i dati, quindi fare clic su *Select Directory* (Seleziona directory).
** Fare clic su *Browse* (Sfoglia) per aprire la finestra di dialogo Browse Directories (Sfoglia directory) e completare la seguente procedura:
+
... Selezionare il cluster di destinazione, la VM di storage (SVM) e il volume su cui si desidera eseguire il ripristino.
... Nella tabella Name (Nome), selezionare un nome di directory da ripristinare.
... Fare clic su *Select Directory* (Seleziona directory).




. Fare clic su *Restore* (Ripristina).
+
Viene avviato il processo di ripristino. Viene creato un lavoro nel back-end per completare il processo di ripristino.

. Se si desidera visualizzare l'avanzamento del processo, dal riquadro di navigazione di sinistra, accedere a *protezione > processi* per visualizzare lo stato del processo di ripristino dall'elenco dei processi.
+
[NOTE]
====
Se un'operazione di ripristino non riesce tra i cluster Cloud Volumes ONTAP ha con un errore NDMP, potrebbe essere necessario aggiungere un percorso AWS esplicito nel cluster di destinazione in modo che la destinazione possa comunicare con la LIF di gestione del cluster del sistema di origine. Questa fase di configurazione viene eseguita utilizzando BlueXP.

====

