---
permalink: data-protection/task_create_resource_pools.html 
sidebar: sidebar 
keywords: creating, resource, pools 
summary: È possibile utilizzare la finestra di dialogo Crea pool di risorse per raggruppare gli aggregati a scopo di provisioning. 
---
= Creazione di pool di risorse
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare la finestra di dialogo Crea pool di risorse per raggruppare gli aggregati a scopo di provisioning.

*Cosa ti serve*

È necessario disporre del ruolo di amministratore dell'applicazione o di amministratore dello storage.

.Fasi
I pool di risorse possono contenere aggregati di cluster diversi, ma lo stesso aggregato non può appartenere a pool di risorse diversi.

. Nel riquadro di spostamento di sinistra, fare clic su *Protection* > *Resource Pools*.
. Nella pagina *Resource Pools*, fare clic su *Create*.
. Seguire le istruzioni nella finestra di dialogo *Crea pool di risorse* per fornire un nome e una descrizione e per aggiungere aggregati come membri al pool di risorse che si desidera creare.

