---
permalink: data-protection/task_remove_protection_relationship_voldtls.html 
sidebar: sidebar 
keywords: remove, protection, relationship,  volume, health details page 
summary: 'È possibile rimuovere una relazione di protezione per eliminare in modo permanente una relazione esistente tra l"origine e la destinazione selezionate, ad esempio quando si desidera creare una relazione utilizzando una destinazione diversa. Questa operazione rimuove tutti i metadati e non può essere annullata.' 
---
= Rimozione di una relazione di protezione dalla pagina Dettagli volume/salute
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile rimuovere una relazione di protezione per eliminare in modo permanente una relazione esistente tra l'origine e la destinazione selezionate, ad esempio quando si desidera creare una relazione utilizzando una destinazione diversa. Questa operazione rimuove tutti i metadati e non può essere annullata.

*Cosa ti serve*

* È necessario disporre del ruolo di amministratore dell'applicazione o di amministratore dello storage.
* È necessario aver impostato l'automazione del flusso di lavoro.


.Fasi
. Nella scheda *Protection* della pagina dei dettagli *Volume / Health*, selezionare dalla topologia la relazione SnapMirror che si desidera rimuovere.
. Fare clic con il pulsante destro del mouse sul nome della destinazione e selezionare *Remove* (Rimuovi) dal menu.
+
Viene visualizzata la finestra di dialogo Rimuovi relazione.

. Fare clic su *continua* per rimuovere la relazione.
+
La relazione viene rimossa dalla pagina Volume / Health Details (Dettagli volume/salute).


